/* SHEET 18 — "Clock Island": a Gothic tower on a hill, crowned by a heap of machinery.
   True 3D masses for perspective and occlusion; every face then gets dense hand-inked detail projected onto it. */
(window.SCENES = window.SCENES || []).push({
  name: 'Clock Island', seed: 4242, ink: '#0c0c0c', theme: 'pencil', reveal: true,
  build(P, n, t) {
    const S = Sketch, D = S.D3, V = S.V3, TAU = S.TAU, lerp = S.lerp, K = '#0c0c0c', Wh = '#ffffff', R = (a, b) => P.r(a, b);
    const CAM = D.camera({ eye: [-1100, -1700, 420], target: [0, 0, 260], f: 1550, cx: 800, cy: 330 });
    const faces = [], add = f => { (Array.isArray(f) ? f : [f]).forEach(x => faces.push(x)); return f; };
    const custom = (c, fn, bias = 4) => faces.push({ custom: fn, c, bias });
    const box = (x0, y0, z0, x1, y1, z1, o = {}) => D.extrude([[x0, y0], [x1, y0], [x1, y1], [x0, y1]], z0, z1, Object.assign({ crease: 0.3, bottom: true }, o));
    const face = (fs, nx, ny, nz) => fs.find(f => Math.abs(f.n[0] - nx) + Math.abs(f.n[1] - ny) + Math.abs(f.n[2] - nz) < 0.05);
    /* orient: map local frame (z = axis) to point A along dir */
    const orient = (fs, A, dir) => { const w = V.norm(dir), u = V.norm(V.cross(Math.abs(w[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0], w)), v = V.cross(w, u); const M = p => [A[0] + u[0] * p[0] + v[0] * p[1] + w[0] * p[2], A[1] + u[1] * p[0] + v[1] * p[1] + w[1] * p[2], A[2] + u[2] * p[0] + v[2] * p[1] + w[2] * p[2]], N = p => [u[0] * p[0] + v[0] * p[1] + w[0] * p[2], u[1] * p[0] + v[1] * p[1] + w[1] * p[2], u[2] * p[0] + v[2] * p[1] + w[2] * p[2]]; return fs.map(f => Object.assign({}, f, { v: f.v.map(M), n: N(f.n), hdir: f.hdir ? N(f.hdir) : undefined })); };
    const pipe = (A, B, r, o = {}) => { const d = V.sub(B, A), L = Math.hypot(d[0], d[1], d[2]); add(orient(D.cylinder(0, 0, r, 0, L, o.seg || 16), A, d)); (o.flanges || []).forEach(t2 => add(orient(D.cylinder(0, 0, r * 1.35, t2 * L - 2, t2 * L + 2, o.seg || 16), A, d))); };
    const planeProj = (O, U, Vv) => (u, v) => { const p = CAM.project([O[0] + U[0] * u + Vv[0] * v, O[1] + U[1] * u + Vv[1] * v, O[2] + U[2] * u + Vv[2] * v]); return p ? [p[0], p[1]] : [0, 0]; };
    /* ---------- 2D ink vocabulary used on facades (all in plane coordinates u,v; pr maps to screen) ---------- */
    const black = pts => P.wash(pts, '#060606', 1, { edge: 0, jit: 0, steps: 1 });
    const white = pts => P.occlude(pts, Wh);
    const polyL = (pts, w = 1, c = K, closed = true) => P.path(closed ? pts.concat([pts[0]]) : pts, { w, c, a: 0.95, rough: 0.25, passes: 1 });
    const archUV = (u0, u1, v0, v1, pointed = true, k = 10) => { const w = u1 - u0, rise = pointed ? w * 0.75 : w / 2, sp = v1 - rise, pts = [[u0, v0], [u0, sp]]; if (pointed) { const Rr = (w * w / 4 + rise * rise) / w; for (let i = 1; i <= k; i++) { const th = Math.PI - (Math.PI - Math.atan2(rise, w / 2 - Rr)) * i / k; pts.push([u0 + Rr + Rr * Math.cos(th), sp + Rr * Math.sin(th)]); } for (let i = k - 1; i >= 1; i--) { const th = Math.PI - (Math.PI - Math.atan2(rise, w / 2 - Rr)) * i / k; pts.push([u1 - Rr - Rr * Math.cos(th), sp + Rr * Math.sin(th)]); } } else for (let i = 1; i < 2 * k; i++) { const th = Math.PI - Math.PI * i / (2 * k); pts.push([u0 + w / 2 + Math.cos(th) * w / 2, sp + Math.sin(th) * w / 2]); } pts.push([u1, sp], [u1, v0]); return pts; };
    const lancet = (pr, u0, u1, v0, v1, o = {}) => { const A = archUV(u0, u1, v0, v1, o.round !== true), S2 = A.map(([u, v]) => pr(u, v)); const fr = archUV(u0 - 3, u1 + 3, v0 - 2, v1 + 3, o.round !== true).map(([u, v]) => pr(u, v)); polyL(fr, 0.8); black(S2); polyL(S2, 1.2);
      const um = (u0 + u1) / 2; if (u1 - u0 > 10) { const a = pr(um, v0), b = pr(um, v1 - (u1 - u0) * 0.55); P.line(a[0], a[1], b[0], b[1], { w: 1, c: Wh, passes: 1, over: 0, rough: 0.1 }); const c = pr(um, v1 - (u1 - u0) * 0.35), rr = Math.hypot(pr(u0, v0)[0] - pr(u1, v0)[0], 0) * 0.16; P.circle(c[0], c[1], rr, { w: 0.8, c: Wh, passes: 1 }); for (let v = v0 + 12; v < v1 - (u1 - u0); v += 12) { const l1 = pr(u0 + 1, v), l2 = pr(u1 - 1, v); P.line(l1[0], l1[1], l2[0], l2[1], { w: 0.5, c: Wh, a: 0.7, passes: 1, over: 0 }); } } };
    const dotsAlong = (pr, u0, v0, u1, v1, step = 5, r = 0.9) => { const L = Math.hypot(u1 - u0, v1 - v0), D2 = []; for (let s = 0; s <= L; s += step) { const q = pr(lerp(u0, u1, s / L), lerp(v0, v1, s / L)); D2.push([q[0], q[1], r]); } P.dots(D2, K, 0.9); };
    const lineUV = (pr, u0, v0, u1, v1, w = 0.9, c = K) => { const a = pr(u0, v0), b = pr(u1, v1); P.line(a[0], a[1], b[0], b[1], { w, c, passes: 1, over: 0, rough: 0.25 }); };
    const puffs2D = (poly, n, rMax) => { for (let i = 0; i < n; i++) { let x0 = 1e9, y0 = 1e9, x1 = -1e9, y1 = -1e9; poly.forEach(([x, y]) => { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }); const x = R(x0, x1), y = R(y0, y1), r = R(3, rMax); if (!S.pip(poly, x, y) || !S.pip(poly, x + r, y) || !S.pip(poly, x - r, y) || !S.pip(poly, x, y + r) || !S.pip(poly, x, y - r)) continue; const b = P.sample(Array.from({ length: 9 }, (_, k) => { const a = k * TAU / 9; return [x + Math.cos(a) * r * R(0.8, 1.15), y + Math.sin(a) * r * R(0.8, 1.15)]; }), true, 2); white(b); for (let q = 0; q < b.length; q += 2) { const [bx, by] = b[q], a = Math.atan2(by - y, bx - x); if (Math.cos(a + 2.3) > -0.2) continue; P.line(bx, by, bx - Math.cos(a) * r * 0.3, by - Math.sin(a) * r * 0.3, { w: 0.5, c: K, passes: 1, over: 0, rough: 0.1 }); } polyL(b, 1); } };


    /* ---------- animation: live groups are drawn once by the pen, then redrawn every frame by the player ---------- */
    const anims = P.anims = [];
    const live = (fn, o = {}) => { const i0 = P.ops.length; fn(0); anims.push(Object.assign({ i0, i1: P.ops.length, fn: (Q, tt) => { const keep = P; P = Q; try { fn(tt); } finally { P = keep; } } }, o)); };
    const detach = fn => { const n0 = faces.length; fn(); return faces.splice(n0); };
    const rotAx = (v, k, th) => { const c = Math.cos(th), s2 = Math.sin(th), kv = V.dot(k, v), kx = V.cross(k, v); return [v[0] * c + kx[0] * s2 + k[0] * kv * (1 - c), v[1] * c + kx[1] * s2 + k[1] * kv * (1 - c), v[2] * c + kx[2] * s2 + k[2] * kv * (1 - c)]; };
    let CLOCK = null, SAILS = null;
    /* ---------- blood-red accent: red strokes laid into the shadow sides for depth ---------- */
    const RED = '#6e0a0c', LGT = V.norm([-0.3, -0.75, 0.55]);
    const redShade = (fs, k = 1, o = {}) => (Array.isArray(fs) ? fs : [fs]).forEach(f => { if (!f.v) return; const lam = V.dot(f.n, LGT); if (lam > (o.max ?? 0.3) && !o.all) return; const old = f.deco; f.deco = (PP, cm, poly) => { if (old) old(PP, cm, poly); let x0 = 1e9, x1 = -1e9; poly.forEach(p => { x0 = Math.min(x0, p[0]); x1 = Math.max(x1, p[0]); }); PP.hatch(poly, { ang: o.ang ?? 34, gap: o.gap ?? 3, c: RED, a: 0.7 * k, w: o.w ?? 0.6, piece: 6, inset: 1.5, fade: (x) => Math.min(1, k * (o.all ? 0.8 : (0.45 - lam) * 1.5) * (o.grad ? 0.2 + (x - x0) / (x1 - x0 + 1) : 1)) }); }; });
    /* ---------- Peter-style 2D marks, studied from the originals ---------- */
    // fringe shading: rows of short strokes perpendicular to the outline, massed on the shadow side
    const fringe = (pts, cx, cy, r, o = {}) => { const rows = o.rows ?? 3, dens = o.every ?? 1; for (let i = 0; i < pts.length; i += dens) { const [x, y] = pts[i], a = Math.atan2(y - cy, x - cx), sh = -Math.cos(a - (o.light ?? -2.4)); if (sh < -0.05) continue; for (let m = 0; m < rows; m++) { const s0 = 1 + m * r * 0.09, L = r * (0.1 + 0.16 * sh) * (1 - m * 0.25); if (L < 1) continue; P.line(x - Math.cos(a) * s0, y - Math.sin(a) * s0, x - Math.cos(a) * (s0 + L), y - Math.sin(a) * (s0 + L), { w: 0.45, c: o.c ?? K, passes: 1, over: 0, rough: 0.1 }); } } };
    const lump = (cx, cy, r, o = {}) => { const k = 12, pts = P.sample(Array.from({ length: k }, (_, i) => { const a = i * TAU / k; return [cx + Math.cos(a) * r * R(0.8, 1.15), cy + Math.sin(a) * r * (o.sq ?? 0.85) * R(0.8, 1.12)]; }), true, 2); white(pts); fringe(pts, cx, cy, r, Object.assign({}, o, { c: o.red ? RED : K })); P.stipple(pts, Math.round(r * r * 0.18), { a: 0.9, r: 0.6, c: K, fade: (x, y) => Math.max(0, ((x - cx) * 0.7 + (y - cy)) / (r * 1.2)) }); polyL(pts, o.w ?? 1.5); if (o.double) polyL(pts.map(([x, y]) => [cx + (x - cx) * 0.86, cy + (y - cy) * 0.86]), 0.5); return pts; };
    const ballStick = (x, y, a, L, w = 0.8, c = K) => { const ex = x + Math.cos(a) * L, ey = y + Math.sin(a) * L; P.line(x, y, ex, ey, { w, c, passes: 1, over: 0, rough: 0.15 }); P.dot(ex, ey, w * 1.8 + 0.4, { c }); };
    const cloudCluster = (x, y, z, n, rMax, bias) => custom([x, y, z], (PP, cm) => { const c = cm.project([x, y, z]); if (!c) return; for (let q = 0; q < n; q++) lump(c[0] + R(-rMax * 1.6, rMax * 1.6), c[1] + R(-rMax * 1.1, rMax * 1.1) - q * 1.4, R(rMax * 0.45, rMax), { rows: 3 }); }, bias);
    const banded = (A, B, r, bands, o = {}) => { pipe(A, B, r, { seg: 18, flanges: bands }); custom([(A[0] + B[0]) / 2, (A[1] + B[1]) / 2, (A[2] + B[2]) / 2], (PP, cm) => { bands.forEach(t2 => { const p = [lerp(A[0], B[0], t2), lerp(A[1], B[1], t2), lerp(A[2], B[2], t2)], d = V.norm(V.sub(B, A)), u = V.norm(V.cross(d, [0, 0, 1])), w = V.cross(u, d); for (let k = 0; k < 10; k++) { const a = Math.PI * 0.6 + k * 0.28, q = V.add(p, V.add(V.mul(u, Math.cos(a) * r * 1.36), V.mul(w, Math.sin(a) * r * 1.36))), s = cm.project(q); if (s) PP.dot(s[0], s[1], 1, { c: K }); } }); }, 6); };

    /* ---------- Peter-style cloud banks (2D, drawn first so the structures sit over them) ---------- */
    const cloudBank = (x0, y0, w, h) => { const n = Math.round(w / 16); for (let row = 0; row < 3; row++) for (let k = 0; k < n; k++) { const t2 = (k + R(-0.3, 0.3)) / (n - 1), bell = Math.sin(Math.PI * Math.min(1, Math.max(0, t2))), r = (8 + 22 * bell) * (1 - row * 0.22) * R(0.8, 1.15), x = x0 + t2 * w, y = y0 - bell * h * (1 - row * 0.4) + row * 18 + r * 0.3; if (bell < 0.15 && row === 0) continue; lump(x, Math.min(y, y0 - r * 0.5 + row * 18), r, { rows: 3, double: r > 20 }); } const base = [[x0 - 6, y0 + 40], [x0 + w + 6, y0 + 40]]; P.line(base[0][0], base[0][1], base[1][0], base[1][1], { w: 1.2, c: K, passes: 1, over: 0 }); for (let k = 1; k < 5; k++) { const a = R(0.05, 0.3), b2 = R(0.6, 0.95); P.line(x0 + w * a, y0 + 40 + k * 5, x0 + w * b2, y0 + 40 + k * 5, { w: 0.5, c: K, passes: 1, over: 0 }); } };
    cloudBank(70, 860, 300, 70);  cloudBank(1100, 150, 200, 40); cloudBank(400, 300, 150, 30);
    for (let i = 0; i < 70; i++) { const x = R(40, 1560), y = R(40, 940); if (x > 480 && x < 1120) continue; if (P.R() < 0.7) lump(x, y, R(2.5, 7), { rows: 2, w: 1 }); else { P.circle(x, y, R(2, 5), { w: 0.8, c: K, passes: 1 }); } }
    /* ================= THE ISLAND: a thick rock slab ================= */
    const isl = []; for (let k = 0; k < 22; k++) { const a = k * TAU / 22; isl.push([Math.cos(a) * R(360, 440) + 20, Math.sin(a) * R(250, 310)]); }
    const ISL = D.extrude(isl, -70, 0, { crease: 0.4 }); add(ISL);
    ISL.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { f.deco = (PP, cm, poly) => { for (let i = 0; i < 6; i++) { const a = poly[0], b = poly[1], c = poly[2], d = poly[3], t2 = R(0.1, 0.9), p1 = [lerp(a[0], b[0], t2), lerp(a[1], b[1], t2)], p2 = [lerp(d[0], c[0], t2 + R(-0.1, 0.1)), lerp(d[1], c[1], t2)]; PP.curve([p1, [lerp(p1[0], p2[0], 0.5) + R(-4, 4), lerp(p1[1], p2[1], 0.5)], p2], { w: 0.6, c: K, rough: 0.5, passes: 1 }); } }; });
    face(ISL, 0, 0, 1).deco = (PP) => { for (let i = 0; i < 160; i++) { const a = R(0, TAU), d = Math.sqrt(R(0, 1)), x = Math.cos(a) * d * 380 + 20, y = Math.sin(a) * d * 260, q = CAM.project([x, y, 0]); if (!q || Math.hypot(x, y) < 120) continue; if (P.R() > 0.5) PP.curve([[q[0], q[1]], [q[0] + R(-1.5, 1.5), q[1] - R(3, 8)]], { w: 0.6, c: K, rough: 0.2, passes: 1 }); else { PP.ellipse(q[0], q[1], R(2, 5), R(1, 2.4), { w: 0.7, c: K, passes: 1 }); } } };

    /* ================= THE CLOCK-LIGHTHOUSE: an octagonal tower ================= */
    const OCT = (r, z0, z1) => D.extrude(Array.from({ length: 8 }, (_, k) => [Math.cos(k * TAU / 8 + TAU / 16) * r, Math.sin(k * TAU / 8 + TAU / 16) * r]), z0, z1, { crease: 0.3 });
    const T1 = OCT(96, 0, 240), T2 = OCT(80, 240, 420), T3 = OCT(66, 420, 470); add(T1); add(T2); add(T3);
    add(OCT(104, 234, 246)); add(OCT(88, 414, 426));
    const octFace = (fs, zlo, zhi, r, fn) => fs.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { const v = f.v, O = [v[0][0], v[0][1], zlo], Ux = V.sub([v[1][0], v[1][1], zlo], O), wid = Math.hypot(Ux[0], Ux[1]), U = V.mul(Ux, 1 / wid); f.deco = () => fn(planeProj(O, U, [0, 0, 1]), wid, zhi - zlo, f.n); });
    octFace(T1, 0, 240, 96, (pr, wid, h, nrm) => { const front = nrm[1] < -0.8; if (front) { const A = archUV(wid * 0.18, wid * 0.82, 0, 150).map(([u, v]) => pr(u, v)); black(A); for (let i = 0; i < 700; i++) { const q = pr(R(wid * 0.22, wid * 0.78), R(6, 140)); if (!S.pip(A, q[0], q[1])) continue; } for (let k = 0; k < 16; k++) { const q = pr(R(wid * 0.24, wid * 0.76), R(10, 130)); const rr = R(4, 10), bl = P.sample(Array.from({ length: 9 }, (_, i) => [q[0] + Math.cos(i * TAU / 9) * rr * R(0.8, 1.2), q[1] + Math.sin(i * TAU / 9) * rr * R(0.8, 1.2)]), true, 1.5); if (!bl.every(([x, y]) => S.pip(A, x, y))) continue; white(bl); polyL(bl, 0.9); P.dot(q[0] + rr * 0.2, q[1], 1, { c: K }); fringe(bl, q[0], q[1], rr, { rows: 2 }); } polyL(A, 1.4); [0, 4, 8].forEach(d => polyL(archUV(wid * 0.18 - d, wid * 0.82 + d, 0, 150 + d * 1.4).map(([u, v]) => pr(u, v)), d ? 0.7 : 1.3)); }
      else { lancet(pr, wid * 0.2, wid * 0.44, 30, 150); lancet(pr, wid * 0.56, wid * 0.8, 30, 150); }
      lancet(pr, wid * 0.25, wid * 0.75, 170, 228); dotsAlong(pr, 2, 160, wid - 2, 160, 5, 1); dotsAlong(pr, 2, 16, wid - 2, 16, 6, 0.9); for (let v = 20; v < 230; v += 8) if (P.R() > 0.6) { const u0 = R(2, wid - 12); lineUV(pr, u0, v, u0 + R(4, 10), v, 0.45); } });
    octFace(T2, 240, 420, 80, (pr, wid, h, nrm) => { const front = nrm[1] < -0.8 || (nrm[0] < -0.2 && nrm[1] < -0.2); for (let k = 0; k < 3; k++) lancet(pr, wid * (0.1 + k * 0.3), wid * (0.3 + k * 0.3), 250 - 240, 330 - 240, { round: k === 1 }); dotsAlong(pr, 2, 100, wid - 2, 100, 5, 1); for (let v = 110; v < 175; v += 7) lineUV(pr, 1, v, wid - 1, v, 0.35); void front; });
    /* the great clock on the front upper face */
    { const f = T2.find(f => f.n[1] < -0.9), v = f.v, cx = (v[0][0] + v[1][0]) / 2, cy = v[0][1] - 2, cz = 360; CLOCK = [cx, cy, cz];
      add(orient(D.cylinder(0, 0, 44, 0, 8, 36), [cx, cy, cz], [0, -1, 0]));
      custom([cx, cy - 12, cz], (PP, cm) => { const P0 = (a, r) => cm.project([cx + Math.cos(a) * r, cy - 8.2, cz + Math.sin(a) * r]); const ring = r => Array.from({ length: 40 }, (_, i) => P0(i * TAU / 40, r)).map(q => [q[0], q[1]]); white(ring(42)); polyL(ring(42), 1.6); polyL(ring(36), 0.8); for (let i = 0; i < 60; i++) { const a = i * TAU / 60, p1 = P0(a, 36), p2 = P0(a, i % 5 ? 39 : 41.5); PP.line(p1[0], p1[1], p2[0], p2[1], { w: i % 5 ? 0.5 : 1.3, c: K, passes: 1, over: 0 }); } ['XII', 'III', 'VI', 'IX'].forEach((s2, i) => { const q = P0(Math.PI / 2 - i * Math.PI / 2, 29); PP.text(s2, q[0], q[1] + 3, { size: 7, align: 'center', c: K }); }); for (let i = 0; i < 12; i++) { const q = P0(i * TAU / 12, 20); PP.dot(q[0], q[1], 1.2, { c: K }); } const c = P0(0, 0); PP.stipple(ring(40), 400, { a: 0.8, r: 0.6, c: K, fade: (x, y) => Math.max(0, (x - c[0]) / 50) }); }, 30); }
    /* spiral pipe winding round the tower, banded + riveted */
    { const pts = []; for (let k = 0; k <= 60; k++) { const t2 = k / 60, a = -1.2 + t2 * TAU * 1.6, r = t2 < 0.62 ? 118 : 100, z = 20 + t2 * 390; pts.push([Math.cos(a) * r, Math.sin(a) * r, z]); } for (let k = 0; k + 1 < pts.length; k++) { pipe(pts[k], pts[k + 1], 9, { seg: 12 }); if (k % 6 === 3) add(orient(D.cylinder(0, 0, 12.4, -2, 2, 12), pts[k], V.sub(pts[k + 1], pts[k]))); } }
    /* lantern: gallery ring with railing, glazed cage with mullions, cupola, lens, big telescope */
    { const LZ = 470; add(D.cylinder(0, 0, 92, LZ, LZ + 8, 32)); add(D.ringSolid(0, 0, 50, 54, LZ + 8, LZ + 90, 24, { a0: 0, a1: TAU }));
      custom([0, -60, LZ + 50], (PP, cm) => { for (let k = 0; k < 16; k++) { const a = k * TAU / 16, p1 = cm.project([Math.cos(a) * 54, Math.sin(a) * 54, LZ + 8]), p2 = cm.project([Math.cos(a) * 54, Math.sin(a) * 54, LZ + 90]); if (!(p1 && p2)) continue; if (Math.cos(a) * (CAM.eye[0]) + Math.sin(a) * CAM.eye[1] < 0) continue; PP.line(p1[0], p1[1], p2[0], p2[1], { w: 1.2, c: K, passes: 1, over: 0 }); } [LZ + 36, LZ + 64].forEach(z => { const pts = []; for (let k = 0; k <= 32; k++) { const a = k * TAU / 32; pts.push([Math.cos(a) * 54.2, Math.sin(a) * 54.2, z]); } D.polyline3(PP, pts.filter(p => p[0] * CAM.eye[0] + p[1] * CAM.eye[1] > 0), cm, { w: 0.7, c: K }); }); for (let k = 0; k < 40; k++) { const a = k * TAU / 40, p1 = cm.project([Math.cos(a) * 90, Math.sin(a) * 90, LZ + 8]), p2 = cm.project([Math.cos(a) * 90, Math.sin(a) * 90, LZ + 26]); if (p1 && p2 && Math.cos(a) * CAM.eye[0] + Math.sin(a) * CAM.eye[1] > 0) PP.line(p1[0], p1[1], p2[0], p2[1], { w: 0.8, c: K, passes: 1, over: 0 }); } }, 40);
      add(D.revolve(0, 0, Array.from({ length: 10 }, (_, k) => { const a = Math.PI / 2 * k / 9; return [Math.cos(a) * 60 + 0.01, LZ + 90 + Math.sin(a) * 50]; }), { seg: 28 })); add(D.revolve(0, 0, [[8, LZ + 138], [2, LZ + 170], [0.01, LZ + 176]], { seg: 10 }));
      add(D.revolve(0, 0, Array.from({ length: 9 }, (_, k) => { const a = -Math.PI / 2 + Math.PI * k / 8; return [Math.cos(a) * 30 + 0.01, LZ + 50 + Math.sin(a) * 30]; }), { seg: 20 }));
      banded([30, -20, LZ + 60], [240, -180, LZ + 140], 14, [0.1, 0.3, 0.55, 0.8]); add(orient(D.cylinder(0, 0, 22, 0, 10, 24), [240, -180, LZ + 140], [210, -160, 80]));
      /* rays removed: they ran off the top edge */
    }
    /* ================= the village on the island: houses, a windmill, a stair tower ================= */
    { const house = (x, y, w, d, h, rot) => { const c = Math.cos(rot), s = Math.sin(rot), T = ([u, v]) => [x + u * c - v * s, y + u * s + v * c]; const base = [[-w, -d], [w, -d], [w, d], [-w, d]].map(T); const H = D.extrude(base, 0, h, { crease: 0.3 }); add(H); const r0 = T([-w, 0]), r1 = T([w, 0]); add(D.poly3([[...T([-w, -d]), h], [...T([w, -d]), h], [...r1, h + w * 0.9], [...r0, h + w * 0.9]], [x, y, -500], { hdir: [0, 0, 1] })); add(D.poly3([[...T([-w, d]), h], [...T([w, d]), h], [...r1, h + w * 0.9], [...r0, h + w * 0.9]], [x, y, -500], {})); add(D.poly3([[...T([-w, -d]), h], [...T([-w, d]), h], [...r0, h + w * 0.9]], [x + 1000, y, h], {})); add(D.poly3([[...T([w, -d]), h], [...T([w, d]), h], [...r1, h + w * 0.9]], [x - 1000, y, h], {}));
        H.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { const v2 = f.v, O = [v2[0][0], v2[0][1], 0], Ux = V.sub([v2[1][0], v2[1][1], 0], O), wid = Math.hypot(Ux[0], Ux[1]); f.deco = () => { const pr = planeProj(O, V.mul(Ux, 1 / wid), [0, 0, 1]); const n2 = Math.max(1, Math.floor(wid / 22)); for (let k = 0; k < n2; k++) lancet(pr, wid * (k + 0.3) / n2, wid * (k + 0.7) / n2, h * 0.3, h * 0.8, { round: true }); for (let v3 = 6; v3 < h; v3 += 7) if (P.R() > 0.5) { const u0 = R(1, wid - 8); lineUV(pr, u0, v3, u0 + R(3, 8), v3, 0.4); } }; }); };
      house(-260, -120, 34, 26, 60, 0.2); house(-320, 40, 26, 22, 48, -0.3); house(250, -130, 30, 24, 70, 0.1); house(200, 120, 24, 20, 44, 0.5); house(-200, 170, 22, 18, 40, 0.2);
      // windmill on the right
      const wx = 330, wy = -20; add(D.revolve(wx, wy, [[34, 0], [22, 150], [0.01, 150]], { seg: 20 })); add(D.revolve(wx, wy, [[26, 150], [4, 196], [0.01, 196]], { seg: 20 }));
      SAILS = (PP, cm, rot = 0) => { const hub = [wx - 10, wy - 30, 170], hp = cm.project(hub); if (!hp) return; for (let k = 0; k < 4; k++) { const a = 0.4 + rot + k * Math.PI / 2, tip = [hub[0] + Math.cos(a) * 12, hub[1] - 4, hub[2] + Math.sin(a) * 120], side = [hub[0] + Math.cos(a) * 12 + Math.cos(a + Math.PI / 2) * 26, hub[1] - 4, hub[2] + Math.sin(a) * 120 + Math.sin(a + Math.PI / 2) * 26], base2 = [hub[0] + Math.cos(a + Math.PI / 2) * 26 * 0.2, hub[1] - 4, hub[2] + Math.sin(a) * 20 + Math.sin(a + Math.PI / 2) * 20]; const tp = cm.project(tip), sp = cm.project(side), bp = cm.project(base2); if (!(tp && sp && bp)) continue; PP.line(hp[0], hp[1], tp[0], tp[1], { w: 2, c: K, passes: 1, over: 0 }); const sail = [[hp[0] + (tp[0] - hp[0]) * 0.18, hp[1] + (tp[1] - hp[1]) * 0.18], [tp[0], tp[1]], [sp[0], sp[1]], [bp[0], bp[1]]]; white(sail); for (let m = 1; m < 8; m++) { const t2 = m / 8; PP.line(lerp(sail[0][0], sail[1][0], t2), lerp(sail[0][1], sail[1][1], t2), lerp(sail[3][0], sail[2][0], t2), lerp(sail[3][1], sail[2][1], t2), { w: 0.6, c: K, passes: 1, over: 0 }); } PP.line(sail[3][0], sail[3][1], sail[2][0], sail[2][1], { w: 0.8, c: K, passes: 1, over: 0 }); polyL(sail, 1.1); } PP.circle(hp[0], hp[1], 6, { w: 1.4, c: K, passes: 1 }); PP.dot(hp[0], hp[1], 2.4, { c: K }); };
      // a stair tower of stacked drums with a spiral stair around it, left
      const sx = -120, sy = -200; for (let k = 0; k < 5; k++) add(D.cylinder(sx, sy, 26 - k * 3, k * 36, k * 36 + 32, 20)); for (let k = 0; k < 30; k++) { const a = k * 0.5, z = k * 6, x = sx + Math.cos(a) * 34, y = sy + Math.sin(a) * 34; add(box(x - 6, y - 6, z, x + 6, y + 6, z + 2.5)); }
    }
    /* ================= satellite rocks, a rope bridge, an airship ================= */
    const SAT = [{ c: [-640, 180], rx: 120, ry: 90, z: 140, d: 150, tip: 0.4 }, { c: [790, -430], rx: 100, ry: 80, z: 360, d: 120, tip: 0.6 }, { c: [-600, 190], rx: 60, ry: 46, z: -260, d: 90, tip: 0.5 }, { c: [128, -775], rx: 150, ry: 105, z: -40, d: 200, tip: 0.5 }];
    SAT.forEach(s => { s.pts = Array.from({ length: 14 }, (_, k) => { const a = k * TAU / 14; return [s.c[0] + Math.cos(a) * s.rx * R(0.8, 1.1), s.c[1] + Math.sin(a) * s.ry * R(0.8, 1.1)]; }); const F = D.extrude(s.pts, s.z - 40, s.z, { crease: 0.4 }); add(F); s.F = F; F.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { f.deco = (PP, cm, poly) => { for (let i = 0; i < 3; i++) { const t2 = R(0.2, 0.8); PP.line(lerp(poly[0][0], poly[1][0], t2), lerp(poly[0][1], poly[1][1], t2), lerp(poly[3][0], poly[2][0], t2), lerp(poly[3][1], poly[2][1], t2), { w: 0.5, c: K, rough: 0.6, passes: 1 }); } }; }); s.z1 = s.z; s.z = s.z - 40; });
    { // left rock: a domed chapel with a bell cote
      const [x, y] = SAT[0].c, z = SAT[0].z1; add(D.extrude([[x - 40, y - 30], [x + 40, y - 30], [x + 40, y + 30], [x - 40, y + 30]], z, z + 60, { crease: 0.3 }));
      add(D.cylinder(x, y, 30, z + 60, z + 76, 24)); add(D.revolve(x, y, Array.from({ length: 9 }, (_, k) => { const a = Math.PI / 2 * k / 8; return [Math.cos(a) * 32 + 0.01, z + 76 + Math.sin(a) * 30]; }), { seg: 24 })); add(D.cylinder(x, y, 7, z + 106, z + 124, 10)); add(D.revolve(x, y, [[9, z + 124], [0.01, z + 146]], { seg: 10 }));
      custom([x, y - 40, z + 30], (PP, cm) => { const pr = planeProj([x - 40, y - 30.5, z], [1, 0, 0], [0, 0, 1]); lancet(pr, 30, 50, 0, 40, { round: true }); lancet(pr, 8, 20, 18, 44); lancet(pr, 60, 72, 18, 44); dotsAlong(pr, 2, 52, 78, 52, 4, 0.9); }, 20);
      // a tree of lumps
      custom([x + 60, y + 20, z + 60], (PP, cm) => { const b = cm.project([x + 70, y + 30, z]); if (!b) return; PP.line(b[0], b[1], b[0] + 2, b[1] - 40, { w: 3, c: K, passes: 1, over: 0 }); for (let q = 0; q < 7; q++) lump(b[0] + R(-16, 18), b[1] - 44 - R(0, 28), R(7, 13), { rows: 3 }); }, 60);
    }
    { // right rock: a water tower on trestle legs
      const [x, y] = SAT[1].c, z = SAT[1].z1; [[-24, -24], [24, -24], [24, 24], [-24, 24]].forEach(([u, v]) => pipe([x + u, y + v, z], [x + u * 0.6, y + v * 0.6, z + 110], 3.5, { seg: 8 }));
      [40, 80].forEach(h => { const k = 1 - h / 110 * 0.4; [[-1, -1, 1, -1], [1, -1, 1, 1], [1, 1, -1, 1], [-1, 1, -1, -1]].forEach(([a, b, c, d]) => pipe([x + a * 24 * k, y + b * 24 * k, z + h], [x + c * 24 * k, y + d * 24 * k, z + h], 1.6, { seg: 6 })); });
      add(D.revolve(x, y, [[34, z + 110], [36, z + 116], [36, z + 170], [30, z + 176], [0.01, z + 196]], { seg: 28 }));
      banded([x, y, z + 20], [x, y - 60, z + 20], 5, [0.3, 0.6]);
    }
    { // little rocks: a lamp post and a ruined arch
      const [x, y] = SAT[2].c, z = SAT[2].z1; pipe([x, y, z], [x, y, z + 70], 2.5, { seg: 8, flanges: [0.1, 0.5] }); pipe([x, y, z + 70], [x + 18, y, z + 74], 1.6, { seg: 6 }); add(D.revolve(x + 18, y, Array.from({ length: 7 }, (_, k) => { const a = -Math.PI / 2 + Math.PI * k / 6; return [Math.cos(a) * 7 + 0.01, z + 62 + Math.sin(a) * 7]; }), { seg: 12 }));
      /* arch replaced by the time engine below */
    }
    /* ================= THE TIME ENGINE on the lower right rock: a Wells-style dish, seat, gear train, hourglass ================= */
    const [ax, ay] = SAT[3].c, az = SAT[3].z1;
    const buildTE = tt => detach(() => { const TE = [], addT = f => { add(f); (Array.isArray(f) ? f : [f]).forEach(x => TE.push(x)); return f; }; const DROT = -tt * 0.5, GW = tt * 0.7;
      addT(box(ax - 100, ay - 56, az, ax + 96, ay + 44, az + 12)); addT(box(ax - 92, ay - 50, az + 12, ax + 88, ay + 38, az + 18));
      // the great dish, standing behind the seat, with its rim, spokes, rings and a red sector
      const DC = [ax + 36, ay + 26, az + 118], DA = V.norm([-0.3, -1, 0]), du = V.norm(V.cross(DA, [0, 0, 1])), dv = [0, 0, 1], DR = 88;
      addT(orient(D.cylinder(0, 0, DR, 0, 5, 44), DC, V.mul(DA, -1))); addT(orient(D.cylinder(0, 0, DR + 4, -1, 1, 44), DC, V.mul(DA, -1)));
      const dp = (a, r, off = 0) => { const q = V.add(V.add(DC, V.mul(DA, 1.2 + off)), V.add(V.mul(du, Math.cos(a) * r), V.mul(dv, Math.sin(a) * r))); return q; };
      custom(V.add(DC, V.mul(DA, 8)), (PP, cm) => { const pj = (a, r) => { const q = cm.project(dp(a, r)); return [q[0], q[1]]; }, ring = r => Array.from({ length: 60 }, (_, i) => pj(i * TAU / 60, r));
        const sec = [pj(0, 0)].concat(Array.from({ length: 12 }, (_, i) => pj(0.35 + i * 0.07 + DROT, 84))); PP.hatch(sec, { ang: 30, gap: 2.2, c: RED, a: 0.85, w: 0.7 }); PP.hatch(sec, { ang: -40, gap: 3, c: RED, a: 0.6, w: 0.5 });
        [84, 76, 58, 40, 22, 10].forEach((r, i) => polyL(ring(r), i === 0 ? 1.6 : 0.7)); for (let k = 0; k < 24; k++) { const a = k * TAU / 24 + DROT, p1 = pj(a, 10), p2 = pj(a, 84); PP.line(p1[0], p1[1], p2[0], p2[1], { w: k % 2 ? 0.5 : 1.1, c: K, passes: 1, over: 0 }); } for (let k = 0; k < 48; k++) { const q = pj(k * TAU / 48 + DROT, 80); PP.dot(q[0], q[1], 0.9, { c: K }); } for (let k = 0; k < 12; k++) { const q = pj(k * TAU / 12 + 0.13 + DROT, 67); PP.text(String(k + 1), q[0], q[1] + 2.5, { size: 5.5, align: 'center', c: K }); }
        const c0 = pj(0, 0); PP.circle(c0[0], c0[1], 6, { w: 1.6, c: K, passes: 1 }); PP.dot(c0[0], c0[1], 2.5, { c: RED });
        // construction lines: the designer's pencil still on the page
        const e1 = pj(Math.PI, 118), e2 = pj(0, 118), e3 = pj(Math.PI / 2, 118), e4 = pj(-Math.PI / 2, 110); PP.line(e1[0], e1[1], e2[0], e2[1], { w: 0.35, c: K, a: 0.5, passes: 1, over: 0 }); PP.line(e3[0], e3[1], e4[0], e4[1], { w: 0.35, c: K, a: 0.5, passes: 1, over: 0 }); polyL(ring(104), 0.3, K); }, 14);
      addT(orient(D.cylinder(0, 0, 9, 0, 22, 16), DC, DA)); pipe([DC[0] + 8, DC[1] + 20, az + 18], [DC[0], DC[1], DC[2]], 6, { seg: 10, flanges: [0.3, 0.7] }); pipe([DC[0] - 40, DC[1] + 30, az + 18], V.add(DC, V.mul(du, -30)), 3.5, { seg: 8 }); pipe([DC[0] + 50, DC[1] + 20, az + 18], V.add(DC, V.mul(du, 30)), 3.5, { seg: 8 });
      // the seat, its backrest and armrests
      const sx = ax - 6, sy = ay - 20; addT(box(sx - 22, sy - 20, az + 18, sx + 22, sy + 16, az + 44)); addT(box(sx - 24, sy + 12, az + 44, sx + 24, sy + 18, az + 98)); addT(box(sx - 26, sy - 20, az + 44, sx - 20, sy + 16, az + 60)); addT(box(sx + 20, sy - 20, az + 44, sx + 26, sy + 16, az + 60));
      custom([sx, sy + 10, az + 70], (PP, cm) => { const pr = planeProj([sx - 24, sy + 11.5, az + 44], [1, 0, 0], [0, 0, 1]); for (let k = 0; k < 4; k++) for (let m = 0; m < 3; m++) { const q = pr(8 + k * 11, 12 + m * 14); PP.dot(q[0], q[1], 1.1, { c: K }); } }, 2);
      // control console with levers and two gauges
      const cx2 = ax - 60, cy2 = ay - 36; addT(box(cx2 - 14, cy2 - 12, az + 18, cx2 + 14, cy2 + 12, az + 58)); [[-6, 30, 0.5], [6, 26, -0.4]].forEach(([u, L, a]) => { const tip = [cx2 + u + Math.sin(a) * 10, cy2 - 4, az + 58 + L]; pipe([cx2 + u, cy2, az + 58], tip, 1.6, { seg: 6 }); addT(D.revolve(tip[0], tip[1], Array.from({ length: 7 }, (_, k) => { const b = -Math.PI / 2 + Math.PI * k / 6; return [Math.cos(b) * 5 + 0.01, tip[2] + Math.sin(b) * 5]; }), { seg: 10 })); });
      [[cx2 - 5, az + 44, 7], [cx2 + 6, az + 30, 5]].forEach(([gx, gz, gr]) => { addT(orient(D.cylinder(0, 0, gr, 0, 3, 18), [gx, cy2 - 12, gz], [0, -1, 0])); custom([gx, cy2 - 16, gz], (PP, cm) => { const q = cm.project([gx, cy2 - 15.2, gz]); if (!q) return; const rr = gr * 0.78; PP.circle(q[0], q[1], rr, { w: 0.6, c: K, passes: 1 }); for (let k = 0; k < 9; k++) { const b = Math.PI * 0.8 + k * 0.18; PP.line(q[0] + Math.cos(b) * rr * 0.7, q[1] + Math.sin(b) * rr * 0.7, q[0] + Math.cos(b) * rr, q[1] + Math.sin(b) * rr, { w: 0.4, c: K, passes: 1, over: 0 }); } const na = -0.46 + 0.6 * Math.sin(tt * 2.3 + gx); PP.line(q[0], q[1], q[0] + Math.cos(na) * rr * 0.9, q[1] + Math.sin(na) * rr * 0.9, { w: 0.8, c: RED, passes: 1, over: 0 }); }, 3); });
      // the hourglass in a three-post frame
      const hx = ax - 72, hy = ay + 12, h0 = az + 18, h1 = az + 150; addT(D.cylinder(hx, hy, 30, h0, h0 + 7, 24)); addT(D.cylinder(hx, hy, 30, h1, h1 + 7, 24)); addT(D.revolve(hx, hy, [[8, h1 + 7], [3, h1 + 22], [0.01, h1 + 24]], { seg: 10 }));
      [0, 1, 2].forEach(k => { const b = -Math.PI / 2 + k * TAU / 3 + 0.4; pipe([hx + Math.cos(b) * 25, hy + Math.sin(b) * 25, h0 + 7], [hx + Math.cos(b) * 25, hy + Math.sin(b) * 25, h1], 2.6, { seg: 8, flanges: [0.1, 0.5, 0.9] }); });
      const HG = D.revolve(hx, hy, Array.from({ length: 17 }, (_, k) => { const t2 = k / 16, zz = lerp(h0 + 9, h1 - 2, t2), w = 3 + 19 * Math.pow(Math.abs(Math.sin(Math.PI * t2 * 2)), 0.7) * (1 - 0.15 * Math.abs(t2 - 0.5)); return [t2 === 0.5 ? 3 : w, zz]; }), { seg: 22 }); HG.forEach(f => { f.tone = 0.08; }); addT(HG);
      custom([hx, hy - 30, (h0 + h1) / 2], (PP, cm) => { const m = (h0 + h1) / 2; const pool = []; for (let k = 0; k <= 16; k++) { const b = k * TAU / 16, q = cm.project([hx + Math.cos(b) * 16, hy + Math.sin(b) * 16, h0 + 24]); if (q) pool.push([q[0], q[1]]); } const tip = cm.project([hx, hy, h0 + 44]); if (tip) { const heap = pool.filter((_, i) => i <= 8).concat([[tip[0], tip[1]]]); PP.stipple(heap, 500, { a: 0.9, r: 0.55, c: K }); } const top = []; for (let k = 0; k <= 16; k++) { const b = k * TAU / 16, q = cm.project([hx + Math.cos(b) * 14, hy + Math.sin(b) * 14, m + 34]); if (q) top.push([q[0], q[1]]); } const neck = cm.project([hx, hy, m + 4]); if (neck) PP.stipple(top.concat([[neck[0], neck[1]]]), 260, { a: 0.9, r: 0.55, c: K }); const a2 = cm.project([hx, hy, m]), b2 = cm.project([hx, hy, h0 + 44]); if (a2 && b2) { PP.line(a2[0], a2[1], b2[0], b2[1], { w: 0.6, c: RED, passes: 1, over: 0 }); for (let j = 0; j < 6; j++) { const f2 = (tt * 1.6 + j / 6) % 1; PP.dot(lerp(a2[0], b2[0], f2), lerp(a2[1], b2[1], f2), 1.1, { c: RED }); } } }, 30);
      // the gear train on the front edge, faces toward us
      const G1 = [ax + 70, ay - 62, az + 64]; addT(orient(D.gearMesh(0, 0, 40, 18, 0, 7, 0.1 + GW), G1, [0, -1, 0])); const g2a = -0.55, G2 = [G1[0] + Math.cos(g2a) * 58, G1[1], G1[2] + Math.sin(g2a) * 58]; addT(orient(D.gearMesh(0, 0, 22, 10, 0, 7, 0.3 - GW * 1.8), G2, [0, -1, 0])); const G3 = [G1[0] + Math.cos(2.1) * 56, G1[1] - 2, G1[2] + Math.sin(2.1) * 56]; addT(orient(D.gearMesh(0, 0, 20, 9, 0, 7, -GW * 2), G3, [0, -1, 0]));
      [[G1, 40, GW], [G2, 22, -GW * 1.8], [G3, 20, -GW * 2]].forEach(([G, r, gr0]) => { addT(orient(D.cylinder(0, 0, r * 0.3, 0, 12, 14), G, [0, -1, 0])); custom([G[0], G[1] - 14, G[2]], (PP, cm) => { const u = [1, 0, 0], v = [0, 0, 1], pj = (b, rr) => cm.project([G[0] + Math.cos(b) * rr, G[1] - 7.3, G[2] + Math.sin(b) * rr]); const ring = rr => Array.from({ length: 30 }, (_, i) => { const q = pj(i * TAU / 30, rr); return [q[0], q[1]]; }); polyL(ring(r * 0.72), 0.7); if (r > 30) { for (let k = 0; k < 6; k++) { const b = k * TAU / 6 + 0.2 + gr0, b2 = b + TAU / 6 - 0.35; const win = [pj(b, r * 0.36), pj(b, r * 0.66), pj((b + b2) / 2, r * 0.69), pj(b2, r * 0.66), pj(b2, r * 0.36)].map(q => [q[0], q[1]]); black(win); } } for (let k = 0; k < 8; k++) { const q = pj(k * TAU / 8 + gr0, r * 0.5 > 12 ? r * 0.3 : r * 0.5); PP.dot(q[0], q[1], 0.9, { c: Wh }); } void u; void v; }, 12); });
      // a coil spring and a riveted exhaust stack with steam lumps
      custom([ax + 80, ay + 10, az + 60], (PP, cm) => { const pts = D.helix(ax + 86, ay + 14, 8, az + 18, az + 110, 11, 12); D.polyline3(PP, pts, cm, { w: 1.1, c: K }); }, 4);
      banded([ax - 30, ay + 36, az + 18], [ax - 30, ay + 36, az + 200], 8, [0.2, 0.45, 0.7, 0.95]); custom([ax - 30, ay + 36, az + 230], (PP, cm) => { const b = cm.project([ax - 30, ay + 36, az + 204]); if (!b) return; Array.from({ length: 7 }, (_, q) => (tt * 0.22 + q / 7) % 1).sort((m, n) => n - m).forEach((ph, q) => lump(b[0] + Math.sin(ph * 6 + q) * 8 + ph * 40, b[1] - 8 - ph * 130, 4 + ph * 13, { rows: 3, red: q === 2 })); }, 60);
      // wiring between the parts
      custom([ax, ay - 40, az + 30], (PP, cm) => { const A = cm.project([cx2 + 14, cy2, az + 40]), B = cm.project([G1[0] - 40, G1[1], G1[2] - 20]), C = cm.project([hx + 26, hy - 10, az + 90]); if (A && B) PP.curve([[A[0], A[1]], [(A[0] + B[0]) / 2, Math.max(A[1], B[1]) + 16], [B[0], B[1]]], { w: 0.8, c: K, rough: 0.2, passes: 1 }); if (A && C) PP.curve([[A[0], A[1]], [(A[0] + C[0]) / 2 - 10, (A[1] + C[1]) / 2 + 12], [C[0], C[1]]], { w: 0.7, c: RED, rough: 0.2, passes: 1 }); }, 3);
      // the pendulum arm reaching off the front edge
      addT(box(ax - 150, ay - 48, az, ax - 134, ay - 32, az + 30)); pipe([ax - 142, ay - 40, az + 24], [ax - 230, ay - 40, az + 6], 3.5, { seg: 8, flanges: [0.2, 0.9] }); addT(orient(D.cylinder(0, 0, 8, -6, 6, 14), [ax - 230, ay - 40, az + 6], [0, 1, 0]));
      redShade(TE, 1.6, { max: 0.5, gap: 2.4 }); });
    /* ================= a wind-up key sticking out of the tower's flank ================= */
    const KEY = { A: [-92, -22, 150], d: V.norm([-1, -0.25, 0]) }; KEY.E = V.add(KEY.A, V.mul(KEY.d, 90)); KEY.ax2 = V.norm(V.cross(KEY.d, [0, 0, 1]));
    pipe(KEY.A, KEY.E, 6, { seg: 12, flanges: [0.15, 0.85] }); add(orient(D.cylinder(0, 0, 10, -8, 8, 16), KEY.E, KEY.d));
    const buildKey = th => detach(() => { const { d, E } = KEY, ax2 = rotAx(KEY.ax2, d, th), fs = [];
      [-1, 1].forEach(s2 => { const Cb = V.add(V.add(E, V.mul(d, 22)), rotAx([0, 0, s2 * 34], d, th)); [1, -1].forEach(sg => fs.push(...orient(D.ringSolid(0, 0, 14, 36, -4, 4, 28, { a0: 0, a1: TAU }), Cb, V.mul(ax2, sg)))); });
      fs.push(...orient(D.cylinder(0, 0, 9, -5, 5, 14), V.add(E, V.mul(d, 16)), ax2)); redShade(fs, 1.2, { max: 0.5 }); add(fs); });
    { // rope-and-plank bridge from the main island to the left rock
      const A = [-330, 120, 0], B = [SAT[0].c[0] + 60, SAT[0].c[1] - 20, SAT[0].z1];
      custom([(A[0] + B[0]) / 2, (A[1] + B[1]) / 2, (A[2] + B[2]) / 2 - 20], (PP, cm) => { const at = (t2, dz, off) => { const p = [lerp(A[0], B[0], t2), lerp(A[1], B[1], t2) + off, lerp(A[2], B[2], t2) - 50 * Math.sin(Math.PI * t2) + dz]; return cm.project(p); }; const n = 30; for (let k = 0; k <= n; k++) { const t2 = k / n, a = at(t2, 0, -10), b = at(t2, 0, 10), c = at(t2, 26, -10); if (!(a && b && c)) continue; PP.line(a[0], a[1], b[0], b[1], { w: 2.2, c: K, passes: 1, over: 0 }); PP.line(a[0], a[1], c[0], c[1], { w: 0.6, c: K, passes: 1, over: 0 }); } [[-10, 26], [10, 26], [-10, 0], [10, 0]].forEach(([off, dz]) => { const pts = []; for (let k = 0; k <= n; k++) { const q = at(k / n, dz, off); if (q) pts.push([q[0], q[1]]); } PP.path(pts, { w: dz ? 0.9 : 1.2, c: K, rough: 0.2, passes: 1 }); }); }, 400);
    }
    const AIR = detach(() => { // the airship: a banded riveted envelope with fins and a gondola
      const C = [-520, -40, 520], dir = [0.84, -0.4, 0.06];
      const prof = Array.from({ length: 13 }, (_, k) => { const a = -Math.PI / 2 + Math.PI * k / 12; return [Math.cos(a) * 46 + 0.01, (Math.sin(a) + 1) * 110 - 110]; });
      const env = orient(D.revolve(0, 0, prof, { seg: 26 }), C, dir); add(env);
      [-60, -20, 20, 60].forEach(t2 => add(orient(D.cylinder(0, 0, 47 * Math.sqrt(1 - (t2 / 110) ** 2) + 1.5, t2 - 2, t2 + 2, 26), C, dir)));
      const P3 = t2 => V.add(C, V.mul(V.norm(dir), t2)); const tail = P3(-96);
      add(D.poly3([V.add(tail, [0, 0, 8]), V.add(P3(-60), [0, 0, 36]), V.add(P3(-112), [0, 0, 56]), V.add(P3(-120), [0, 0, 14])], V.add(tail, [0, -300, 0]), {}));
      add(D.poly3([V.add(tail, [0, 0, -8]), V.add(P3(-60), [0, 0, -36]), V.add(P3(-112), [0, 0, -52]), V.add(P3(-120), [0, 0, -14])], V.add(tail, [0, -300, 0]), {}));
      const g = V.add(C, [0, 0, -62]); add(D.extrude([[g[0] - 34, g[1] - 10], [g[0] + 34, g[1] - 4], [g[0] + 34, g[1] + 10], [g[0] - 34, g[1] + 4]], g[2] - 14, g[2], { crease: 0.3 }));
      custom(g, (PP, cm) => { [-28, 0, 28].forEach(u => { const a = cm.project([g[0] + u, g[1], g[2]]), b = cm.project(V.add(C, V.mul(V.norm(dir), u)).map((v, i) => i === 2 ? v - 44 : v)); if (a && b) PP.line(a[0], a[1], b[0], b[1], { w: 0.7, c: K, passes: 1, over: 0 }); }); const pr = planeProj([g[0] - 34, g[1] - 10.5, g[2] - 14], [0.996, 0.09, 0], [0, 0, 1]); for (let k = 0; k < 7; k++) lancet(pr, 4 + k * 9.4, 10 + k * 9.4, 3, 11, { round: true }); const pp = cm.project(P3(112)); if (pp) { for (let k = 0; k < 4; k++) { const a = k * Math.PI / 2 + 0.5; PP.line(pp[0], pp[1], pp[0] + Math.cos(a) * 3, pp[1] + Math.sin(a) * 18, { w: 2, c: K, passes: 1, over: 0 }); } } }, 50);
    });
    cloudCluster(-150, -110, 300, 9, 18, 200); cloudCluster(130, -110, 200, 7, 15, 200); cloudCluster(-380, -60, 60, 7, 16, 120); cloudCluster(120, -100, 520, 6, 14, 300);

    redShade(T1, 0.9, { grad: true }); redShade(T2, 0.8, { grad: true }); redShade(ISL, 0.7, { gap: 3.6 }); SAT.forEach(s => redShade(s.F, 0.8));
    /* ================= render the structure ================= */
    const RO = { ink: K, paper: Wh, light: [-0.3, -0.75, 0.55], ambient: 0.04, w: 1.4, rough: 0.3, zw: 0, hatchMin: 0.06, rich: true, darken: 1.6, gap: 3.2, stipple: true, style: 'layered' };
    D.render(P, faces, CAM, RO);
    const drift = tt => ({ x: 9 * Math.sin(tt * 0.33), y: 5 * Math.sin(tt * 0.8) });
    live(() => D.render(P, AIR, CAM, RO), { cache: true, fps: 0, xf: drift });
    live(tt => SAILS(P, CAM, -tt * 0.9), { fps: 30 });
    live(tt => D.render(P, buildKey(tt * 0.9), CAM, RO), { cache: true, fps: 15 });
    live(tt => D.render(P, buildTE(tt), CAM, RO), { cache: true, fps: 12 });
    live(tt => { // the clock keeps real time; a red seconds hand ticks
      const [cx, cy, cz] = CLOCK, P0 = (a, r) => CAM.project([cx + Math.cos(a) * r, cy - 8.4, cz + Math.sin(a) * r]), now = new Date(), sec = now.getSeconds() + (tt ? 0 : 0), mn = now.getMinutes() + sec / 60, hr = (now.getHours() % 12) + mn / 60;
      const c = P0(0, 0), h = P0(Math.PI / 2 - hr / 12 * TAU, 20), m = P0(Math.PI / 2 - mn / 60 * TAU, 32), sc = P0(Math.PI / 2 - sec / 60 * TAU, 36), sb = P0(Math.PI / 2 - sec / 60 * TAU + Math.PI, 9);
      P.line(c[0], c[1], h[0], h[1], { w: 2.6, c: K, passes: 1, over: 0 }); P.line(c[0], c[1], m[0], m[1], { w: 1.4, c: K, passes: 1, over: 0 }); P.line(sb[0], sb[1], sc[0], sc[1], { w: 0.7, c: RED, passes: 1, over: 0 }); P.dot(c[0], c[1], 3, { c: K }); P.dot(c[0], c[1], 1.2, { c: RED }); }, { fps: 4 });
    live(tt => { // the lighthouse lens sweeps a beam of fine lines round the sky
      const O = [0, 0, 520], phi = -1.2 + tt * 0.45, toCam = V.norm([CAM.eye[0], CAM.eye[1], 0]), dir = [Math.cos(phi), Math.sin(phi), 0], f = V.dot(dir, toCam); if (f < -0.35) return; const vis = Math.min(1, (f + 0.35) * 2.2);
      for (let k = 0; k <= 12; k++) { const ang = phi + (k / 12 - 0.5) * 0.24, zz = 520 + (k / 12 - 0.5) * 50; let prev = null; for (let sgm = 0; sgm <= 16; sgm++) { const rr = 62 + sgm * 70, q = CAM.project([Math.cos(ang) * rr, Math.sin(ang) * rr, zz + sgm * 4]); if (!q) break; if (prev && (sgm + k) % 2 === 0) P.line(prev[0], prev[1], q[0], q[1], { w: k % 6 === 0 ? 0.8 : 0.45, c: k % 4 === 1 ? RED : K, a: vis * 0.5 * (1 - sgm / 17), passes: 1, over: 0, rough: 0.1 }); prev = q; } } }, { fps: 30 });

    /* ================= THE UNDERWORLD hanging beneath each rock (2D, Peter-style) ================= */
    const EYES = [];
    const underworld = (pts, z, maxD, o = {}) => {
      const rim = pts.map(([x, y]) => CAM.project([x, y, z])).filter(Boolean).map(q => [q[0], q[1]]);
      let minX = 1e9, maxX = -1e9; rim.forEach(([x]) => { minX = Math.min(minX, x); maxX = Math.max(maxX, x); });
      const lowY = x => { let best = -1e9; for (let i = 0; i < rim.length; i++) { const a = rim[i], b = rim[(i + 1) % rim.length]; if ((a[0] - x) * (b[0] - x) > 0 || a[0] === b[0]) continue; const t2 = (x - a[0]) / (b[0] - a[0]); best = Math.max(best, a[1] + (b[1] - a[1]) * t2); } return best; };
      const N = Math.max(12, Math.round((maxX - minX) / 7)), topC = [], botC = [];
      const tipT = o.tip ?? 0.5, lob = R(0, 9);
      for (let k = 0; k <= N; k++) { const t2 = k / N, x = lerp(minX + 1, maxX - 1, t2), y = lowY(x); if (y < -1e8) continue; topC.push([x, y - 3]);
        const bell = Math.pow(Math.max(0, 1 - Math.pow(Math.abs(t2 - tipT) / Math.max(tipT, 1 - tipT), 1.3)), 1.1);
        let d = maxD * bell * (0.82 + 0.18 * Math.sin(t2 * 21 + lob)) + (k % 5 === 2 ? R(8, 26) * bell : 0) + 6; botC.push([x, Math.min(o.floor ?? 975, y + d)]); }
      const mass = topC.concat(botC.slice().reverse());
      black(mass);
      const bb = { x0: minX, x1: maxX, y0: Math.min(...topC.map(p => p[1])), y1: Math.max(...botC.map(p => p[1])) };
      // a band of lumps crowding the seam under the rock (Peter's "cauliflower" rim)
      const placed = [];
      topC.forEach(([x, y], i) => { if (i % 2) return; const r = R(5, 11) * (o.s ?? 1); if (!S.pip(mass, x, y + r + 4)) return; placed.push([x, y + r + 2, r]); lump(x, y + r + 2, r, { rows: 2, w: 1.1 }); });
      // white veins with ball-and-stick branches
      for (let k = 0; k < (o.veins ?? 14); k++) { let x = R(minX + 20, maxX - 20), y = lowY(x) + 14, a = Math.PI / 2 + R(-0.35, 0.35); const vp = []; for (let i = 0; i < 60; i++) { a += R(-0.16, 0.16); x += Math.cos(a) * 5; y += Math.sin(a) * 5; if (!S.pip(mass, x, y + 8)) break; vp.push([x, y]); } if (vp.length < 6) continue; const L = [], Rr = [], W0 = R(4, 9) * (o.s ?? 1); vp.forEach((p, i) => { const q = vp[Math.min(vp.length - 1, i + 1)], oo = vp[Math.max(0, i - 1)], tx = q[0] - oo[0], ty = q[1] - oo[1], l = Math.hypot(tx, ty) || 1, w = W0 * (1 - i / vp.length) + 1.5; L.push([p[0] - ty / l * w, p[1] + tx / l * w]); Rr.push([p[0] + ty / l * w, p[1] - tx / l * w]); }); const poly = L.concat(Rr.slice().reverse()); white(poly); P.path(Rr.map(([x2, y2], i) => [lerp(x2, vp[i][0], 0.3), lerp(y2, vp[i][1], 0.3)]), { w: 0.9, c: RED, a: 0.8, rough: 0.2, passes: 1 }); polyL(poly, 0.9); for (let i = 2; i < vp.length - 1; i += 2) { const [px, py] = vp[i], q = vp[i + 1], a2 = Math.atan2(q[1] - py, q[0] - px), w = W0 * (1 - i / vp.length) + 1.5; P.line(L[i][0], L[i][1], Rr[i][0], Rr[i][1], { w: 0.5, c: K, passes: 1, over: 0 }); ballStick(L[i][0], L[i][1], a2 + 1.5 + R(-0.3, 0.3), w * 1.2 + 3, 0.6, Wh); ballStick(Rr[i][0], Rr[i][1], a2 - 1.5 + R(-0.3, 0.3), w * 1.2 + 3, 0.6, Wh); } }
      // pods, lumps, rings, eyes, seed-cases packed into the dark
      for (let i = 0; i < (o.tries ?? 16000); i++) { const r = R(3, o.rMax ?? 24), x = R(bb.x0, bb.x1), y = R(bb.y0 + 10, bb.y1); if (!S.pip(mass, x, y) || !S.pip(mass, x, y + r) || !S.pip(mass, x - r, y) || !S.pip(mass, x + r, y) || placed.some(([a, b, c]) => Math.hypot(x - a, y - b) < c + r + 1.8)) continue; placed.push([x, y, r]); const k = P.R();
        if (k < 0.34) lump(x, y, r, { rows: 3, double: r > 12, red: P.R() < 0.18 });
        else if (k < 0.48) { white(Array.from({ length: 18 }, (_, q) => [x + Math.cos(q * TAU / 18) * r, y + Math.sin(q * TAU / 18) * r])); for (let m = 1; m <= 4; m++) P.circle(x, y, r * m / 4, { w: m === 4 ? 1.2 : 0.6, c: K, passes: 1 }); P.stipple(Array.from({ length: 12 }, (_, q) => [x + Math.cos(q * TAU / 12) * r, y + Math.sin(q * TAU / 12) * r]), Math.round(r * r * 0.3), { a: 0.9, r: 0.6, c: K, fade: (px, py) => Math.max(0, (px - x + py - y) / (r * 1.4)) }); }
        else if (k < 0.6) { const pts2 = P.sample(Array.from({ length: 10 }, (_, q) => [x + Math.cos(q * TAU / 10) * r * 0.5, y + Math.sin(q * TAU / 10) * r]), true, 2); white(pts2); polyL(pts2, 1.1); for (let m = -3; m <= 3; m++) P.dot(x, y + m * r * 0.22, 1.1, { c: K }); fringe(pts2, x, y, r * 0.7, { rows: 2 }); }
        else if (k < 0.7) { EYES.push([x, y, r]); white(Array.from({ length: 16 }, (_, q) => [x + Math.cos(q * TAU / 16) * r, y + Math.sin(q * TAU / 16) * r * 0.75])); P.ellipse(x, y, r, r * 0.75, { w: 1.2, c: K, passes: 1 }); P.circle(x, y, r * 0.42, { w: 0.9, c: K, passes: 1 }); P.circle(x, y, r * 0.32, { w: 1.6, c: RED, passes: 1 }); P.wash(Array.from({ length: 10 }, (_, q) => [x + Math.cos(q * TAU / 10) * r * 0.2, y + Math.sin(q * TAU / 10) * r * 0.2]), '#050505', 1, { edge: 0, steps: 1, jit: 0 }); P.dot(x - r * 0.1, y - r * 0.1, 1.2, { c: Wh }); for (let m = 0; m < 9; m++) { const a = Math.PI + m * Math.PI / 8; P.line(x + Math.cos(a) * r, y + Math.sin(a) * r * 0.75, x + Math.cos(a) * r * 1.25, y + Math.sin(a) * r * 0.95, { w: 0.6, c: Wh, passes: 1, over: 0 }); } }
        else if (k < 0.8 && r > 8) { const n = Math.floor(r / 3); for (let m = 0; m < n; m++) { const rr = r * (1 - m / n); white(Array.from({ length: 12 }, (_, q) => [x + Math.cos(q * TAU / 12) * rr, y - (r - rr) * 0.6 + Math.sin(q * TAU / 12) * rr * 0.6])); P.ellipse(x, y - (r - rr) * 0.6, rr, rr * 0.6, { w: 0.8, c: K, passes: 1 }); } }
        else { P.dot(x, y, Math.min(2.6, r * 0.2), { c: Wh, a: 1 }); if (r > 6) P.circle(x, y, r * 0.5, { w: 0.5, c: Wh, passes: 1 }); } }
      // white star-dust in the gaps
      for (let i = 0; i < (o.dust ?? 600); i++) { const x = R(bb.x0, bb.x1), y = R(bb.y0, bb.y1); if (S.pip(mass, x, y) && !placed.some(([a, b, c]) => Math.hypot(x - a, y - b) < c + 1)) P.dot(x, y, R(0.4, 0.9), { c: Wh, a: 1 }); }
      // hanging roots and droplet threads from the underside
      for (let k = 0; k < (o.roots ?? 36); k++) { const [x, y] = botC[Math.floor(R(1, botC.length - 1))]; const L = R(18, 80) * (o.s ?? 1), pts2 = [[x, y - 3]]; let a = Math.PI / 2 + R(-0.25, 0.25), px = x, py = y; for (let s = 0; s < L; s += 5) { a += R(-0.2, 0.2); px += Math.cos(a) * 5; py += Math.sin(a) * 5; pts2.push([px, py]); } if (py > 978) continue; P.path(pts2, { w: k % 3 ? 0.9 : 2, c: K, rough: 0.2, passes: 1 }); if (k % 3 === 0) { const d = P.sample([[px, py - 3], [px + 3.5, py + 2], [px, py + 7], [px - 3.5, py + 2]], true, 1.5); white(d); polyL(d, 1); P.dot(px - 1, py + 2, 0.9, { c: K }); } else P.dot(px, py, 1.6, { c: K }); }
      polyL(mass, 1.6);
    };
    underworld(isl, -70, 330, { veins: 16 });
    SAT.forEach(s => underworld(s.pts, s.z, s.d, { veins: 4, s: 0.6, rMax: 12, tries: 5000, roots: 12, dust: 150, tip: s.tip }));
    live(tt => EYES.forEach(([x, y, r], i) => { const ph = (tt + i * 1.37) % 6.5; if (!tt || ph > 0.28) return; const e = Array.from({ length: 16 }, (_, q) => [x + Math.cos(q * TAU / 16) * r * 1.04, y + Math.sin(q * TAU / 16) * r * 0.8]); white(e); P.ellipse(x, y, r, r * 0.75, { w: 1.2, c: K, passes: 1 }); P.curve([[x - r, y], [x, y + r * 0.3], [x + r, y]], { w: 1.3, c: K, passes: 1, rough: 0.1 }); for (let m = 0; m < 5; m++) { const u = -0.7 + m * 0.35, lx = x + u * r, ly = y + r * 0.3 * (1 - u * u); P.line(lx, ly, lx + u * 3, ly + r * 0.3, { w: 0.6, c: K, passes: 1, over: 0 }); } }), { fps: 24 });
    /* ================= post-render ink: pendulum, ladder, jellyfish, the eye, an escapement detail ================= */
    { const pv = CAM.project([ax - 230, ay - 40, az + 6]); if (pv) { const L = 170, sw = 0.22, bobAt = a => [pv[0] + Math.sin(a) * L, pv[1] + Math.cos(a) * L];
        [-sw, sw].forEach(a => { const b = bobAt(a); P.line(pv[0], pv[1], b[0], b[1], { w: 0.35, c: K, a: 0.45, passes: 1, over: 0 }); P.circle(b[0], b[1], 22, { w: 0.4, c: K, a: 0.45, passes: 1 }); });
        const arc = []; for (let k = 0; k <= 30; k++) arc.push(bobAt(-sw * 1.25 + k * sw * 2.5 / 30)); P.path(arc.map(([x, y]) => [x, y + 30]), { w: 0.5, c: K, rough: 0.1, passes: 1 }); [arc[0], arc[30]].forEach(([x, y], i) => { const s = i ? 1 : -1; P.line(x, y + 30, x - s * 6, y + 26, { w: 0.6, c: K, passes: 1, over: 0 }); P.line(x, y + 30, x - s * 5, y + 36, { w: 0.6, c: K, passes: 1, over: 0 }); });
        live(() => { const a0 = 0, b = bobAt(a0), nx = Math.cos(a0), ny = -Math.sin(a0); [[-2.4, 1.5], [2.4, 1.5]].forEach(([o]) => P.line(pv[0] + nx * o, pv[1] + ny * o, b[0] + nx * o * 0.6, b[1] + ny * o * 0.6, { w: 1.2, c: K, passes: 1, over: 0 })); for (let t2 = 0.1; t2 < 0.85; t2 += 0.12) { const x = lerp(pv[0], b[0], t2), y = lerp(pv[1], b[1], t2); P.circle(x, y, 1.6, { w: 0.6, c: K, passes: 1 }); }
        const disc = Array.from({ length: 36 }, (_, i) => [b[0] + Math.cos(i * TAU / 36) * 26, b[1] + Math.sin(i * TAU / 36) * 26]); white(disc); const cres = Array.from({ length: 19 }, (_, i) => { const q = -0.6 + i * Math.PI / 18; return [b[0] + Math.cos(q) * 26, b[1] + Math.sin(q) * 26]; }).concat(Array.from({ length: 19 }, (_, i) => { const q = -0.6 + Math.PI - i * Math.PI / 18; return [b[0] + 5 + Math.cos(q) * 20, b[1] + 3 + Math.sin(q) * 20]; })); P.hatch(cres, { ang: 40, gap: 1.8, c: RED, a: 0.9, w: 0.6 }); P.hatch(cres, { ang: -30, gap: 2.6, c: K, a: 0.6, w: 0.45 }); polyL(disc, 1.8); [19, 12, 5].forEach(r => P.circle(b[0], b[1], r, { w: 0.7, c: K, passes: 1 })); P.dot(b[0], b[1], 2, { c: RED }); fringe(disc, b[0], b[1], 26, { rows: 3 }); P.text('T-1', b[0] + 34, b[1] + 4, { size: 8, c: RED }); }, { fps: 0, xf: tt => ({ rot: -0.21 * Math.sin(tt * 2.1), px: pv[0], py: pv[1] }) }); } }
    { const g = CAM.project([-520, -40, 444]); if (g) live(() => { let x = g[0], y = g[1] + 4; const L = [], Rr = []; for (let k = 0; k < 9; k++) { const sway = Math.sin(k * 0.5) * 3; L.push([x - 7 + sway, y + k * 9]); Rr.push([x + 7 + sway, y + k * 9]); } P.path(L, { w: 0.7, c: K, rough: 0.2, passes: 1 }); P.path(Rr, { w: 0.7, c: K, rough: 0.2, passes: 1 }); L.forEach((p, i) => { if (i) P.line(p[0], p[1], Rr[i][0], Rr[i][1], { w: 1.1, c: K, passes: 1, over: 0 }); }); const e = L[L.length - 1]; P.path([[e[0], e[1]], [e[0] - 3, e[1] + 14], [e[0] + 2, e[1] + 24]], { w: 0.6, c: K, rough: 0.2, passes: 1 }); P.dot(e[0] + 2, e[1] + 25, 1.5, { c: K }); }, { fps: 0, xf: tt => { const m = drift(tt); return { x: m.x, y: m.y, rot: 0.09 * Math.sin(tt * 1.3), px: g[0], py: g[1] }; } }); }
    live(tt => { // a drifting jellyfish: fringed bell, ribbed, beaded tentacles
      const jx = 150 + 6 * Math.sin(tt * 0.4), jy = 330 - 9 * Math.sin(tt * 0.9), r = 34 * (1 + 0.05 * Math.sin(tt * 1.8)); const bell = []; for (let k = 0; k <= 24; k++) { const a = Math.PI + k * Math.PI / 24; bell.push([jx + Math.cos(a) * r, jy + Math.sin(a) * r * 0.9]); } for (let k = 0; k <= 10; k++) bell.push([jx + r - k * 2 * r / 10, jy + (k % 2 ? 6 : 0)]); white(bell); for (let k = 1; k < 8; k++) { const a = Math.PI + k * Math.PI / 8; P.curve([[jx, jy - r * 0.85], [jx + Math.cos(a) * r * 0.6, jy + Math.sin(a) * r * 0.5], [jx + Math.cos(a) * r, jy + Math.sin(a) * r * 0.1 + 2]], { w: 0.5, c: K, passes: 1, rough: 0.1 }); } fringe(bell.slice(0, 25), jx, jy, r, { rows: 3, light: -1.2 }); P.stipple(bell, 260, { a: 0.9, r: 0.55, c: RED, fade: (x, y) => Math.max(0, (x - jx) / r) }); polyL(bell, 1.5);
      for (let k = 0; k < 9; k++) { let x = jx - r + 6 + k * (2 * r - 12) / 8, y = jy + 4; const pts = [[x, y]]; for (let s = 0; s < 14 + (k % 3) * 5; s++) { x += Math.sin(s * 0.5 + k - tt * 2.6) * (2.2 + s * 0.08); y += 5 - 0.6 * Math.sin(tt * 1.8); pts.push([x, y]); } P.path(pts, { w: k % 3 ? 0.6 : 1.4, c: k % 4 === 1 ? RED : K, rough: 0.15, passes: 1 }); pts.forEach((p, i) => { if (i % 3 === 2) P.dot(p[0], p[1], k % 3 ? 1 : 1.8, { c: K }); }); } }, { fps: 20 });
    live(tt => { // the floating eye, trailing its nerves
      const ex = 1190, ey = 330 + 7 * Math.sin(tt * 0.7), r = 30, shut = tt > 0 && (tt % 5.3) < 0.22; for (let k = 0; k < 7; k++) { let x = ex + r * 0.7, y = ey - 9 + k * 3, a = -0.3 + k * 0.1; const pts = [[x, y]]; for (let s = 0; s < 16; s++) { a += 0.12 * Math.sin(s * 0.6 + k * 1.7 - tt * 2.2); x += Math.cos(a) * 4; y += Math.sin(a) * 4 + 1.2; pts.push([x, y]); } P.path(pts, { w: k < 2 ? 1.6 : 0.7, c: k === 3 ? RED : K, rough: 0.2, passes: 1 }); P.dot(x, y, 1.3, { c: K }); }
      const ball = Array.from({ length: 36 }, (_, i) => [ex + Math.cos(i * TAU / 36) * r, ey + Math.sin(i * TAU / 36) * r]); white(ball); for (let k = 0; k < 9; k++) { let x = ex + Math.cos(k * 0.7 + 0.2) * r, y = ey + Math.sin(k * 0.7 + 0.2) * r; const pts = [[x, y]]; for (let s = 0; s < 4; s++) { x += (ex - 8 - x) * 0.22 + R(-2, 2); y += (ey - y) * 0.22 + R(-2, 2); pts.push([x, y]); } P.path(pts, { w: 0.45, c: RED, rough: 0.3, passes: 1 }); }
      fringe(ball, ex, ey, r, { rows: 3 }); const ix = ex - 7 + 6 * Math.cos(tt * 0.6), iy = ey - 2 + 4 * Math.sin(tt * 0.9 + 1); if (shut) { polyL(ball, 1.8); P.curve([[ex - r, ey], [ex, ey + 10], [ex + r, ey]], { w: 1.6, c: K, passes: 1, rough: 0.1 }); for (let m = 0; m < 7; m++) { const u = -0.8 + m * 0.27, lx = ex + u * r, ly = ey + 10 * (1 - u * u); P.line(lx, ly, lx + u * 4, ly + 8, { w: 0.8, c: K, passes: 1, over: 0 }); } return; } P.circle(ix, iy, 13, { w: 1.2, c: K, passes: 1 }); for (let k = 0; k < 28; k++) { const a = k * TAU / 28; P.line(ix + Math.cos(a) * 6.5, iy + Math.sin(a) * 6.5, ix + Math.cos(a) * 12.5, iy + Math.sin(a) * 12.5, { w: 0.5, c: k % 2 ? RED : K, passes: 1, over: 0 }); } P.wash(Array.from({ length: 14 }, (_, q) => [ix + Math.cos(q * TAU / 14) * 6, iy + Math.sin(q * TAU / 14) * 6]), '#050505', 1, { edge: 0, steps: 1, jit: 0 }); P.dot(ix - 2, iy - 2, 1.6, { c: Wh }); polyL(ball, 1.8); for (let k = 0; k < 11; k++) { const a = Math.PI * 1.05 + k * 0.09; P.line(ex + Math.cos(a) * r, ey + Math.sin(a) * r, ex + Math.cos(a) * (r + 7), ey + Math.sin(a) * (r + 9), { w: 0.8, c: K, passes: 1, over: 0 }); } }, { fps: 20 });
    { // detail A: the clock's escapement, sketched out in a floating bubble
      const cx = 445, cy = 770, Rb = 64, circ = (r, n = 48) => Array.from({ length: n }, (_, i) => [cx + Math.cos(i * TAU / n) * r, cy + Math.sin(i * TAU / n) * r]);
      white(circ(Rb + 4)); P.line(cx - Rb - 14, cy, cx + Rb + 14, cy, { w: 0.3, c: K, a: 0.45, passes: 1, over: 0 }); P.line(cx, cy - Rb - 14, cx, cy + Rb + 14, { w: 0.3, c: K, a: 0.45, passes: 1, over: 0 });
      live(tt => { const tick = tt * 2, st = Math.floor(tick), WR = (st + Math.min(1, (tick - st) * 7)) * TAU / 30, rock = (st % 2 ? 1 : -1) * 0.11 * Math.min(1, (tick - st) * 7) * (tt ? 1 : 0); const wx = cx - 4, wy = cy + 16, wr = 34, teeth = []; for (let k = 0; k < 15; k++) { const a = k * TAU / 15 + WR; teeth.push([wx + Math.cos(a) * wr * 0.78, wy + Math.sin(a) * wr * 0.78], [wx + Math.cos(a + 0.06) * wr, wy + Math.sin(a + 0.06) * wr], [wx + Math.cos(a + 0.2) * wr * 0.8, wy + Math.sin(a + 0.2) * wr * 0.8]); }
      white(teeth); P.hatch(teeth, { ang: 50, gap: 2.4, c: K, a: 0.5, w: 0.45, fade: (x, y) => Math.max(0, (x - wx + y - wy) / 40 + 0.4) }); polyL(teeth, 1.2); for (let k = 0; k < 5; k++) { const a = k * TAU / 5 + 0.3 + WR; P.line(wx + Math.cos(a) * 6, wy + Math.sin(a) * 6, wx + Math.cos(a) * wr * 0.66, wy + Math.sin(a) * wr * 0.66, { w: 1.6, c: K, passes: 1, over: 0 }); } P.circle(wx, wy, wr * 0.68, { w: 0.9, c: K, passes: 1 }); P.circle(wx, wy, 6, { w: 1.2, c: K, passes: 1 }); P.dot(wx, wy, 2, { c: K });
      const px = wx, py = cy - 36, rp = ([x, y]) => [px + (x - px) * Math.cos(rock) - (y - py) * Math.sin(rock), py + (x - px) * Math.sin(rock) + (y - py) * Math.cos(rock)], anc = [[px, py - 6], [px + 34, py + 18], [px + 30, py + 28], [px + 26, py + 22], [px, py + 6], [px - 26, py + 22], [px - 30, py + 28], [px - 34, py + 18]].map(rp); white(anc); P.hatch(anc, { ang: 35, gap: 1.8, c: RED, a: 0.9, w: 0.6 }); polyL(anc, 1.3); P.circle(px, py, 4, { w: 1, c: K, passes: 1 }); P.dot(px, py, 1.4, { c: K });
      P.line(px, py - 4, px + 6, cy - Rb + 2, { w: 1.4, c: K, passes: 1, over: 0 }); [[px + 32, py + 27], [px - 28, py + 27]].map(rp).forEach(([x, y]) => { P.dot(x, y, 1.8, { c: RED }); });
      const arc = []; for (let k = 0; k <= 12; k++) { const a = -Math.PI / 2 - 0.5 + k / 12; arc.push([px + Math.cos(a) * 20, py + 2 + Math.sin(a) * 20]); } P.path(arc, { w: 0.5, c: RED, passes: 1, rough: 0.1 }); }, { fps: 30 });
      polyL(circ(Rb + 4), 1.8); polyL(circ(Rb), 0.6); fringe(circ(Rb + 4, 60), cx, cy, Rb, { rows: 2 }); for (let k = 0; k < 36; k++) { const a = k * TAU / 36, r1 = Rb + 4, r2 = Rb + (k % 3 ? 7 : 11); P.line(cx + Math.cos(a) * r1, cy + Math.sin(a) * r1, cx + Math.cos(a) * r2, cy + Math.sin(a) * r2, { w: 0.5, c: K, passes: 1, over: 0 }); }
      P.circle(cx + Rb * 0.78, cy - Rb * 0.78, 10, { w: 1.2, c: K, passes: 1 }); P.text('A', cx + Rb * 0.78, cy - Rb * 0.78 + 3.5, { size: 9, align: 'center', c: RED });
      const cl = CAM.project([0, -80, 380]); if (cl) { P.circle(cl[0] + 44, cl[1] - 18, 7, { w: 1, c: K, passes: 1 }); P.text('A', cl[0] + 44, cl[1] - 15, { size: 7, align: 'center', c: RED }); }
      P.text('ESCAPEMENT', cx, cy + Rb + 24, { size: 7, align: 'center', c: K, a: 0.8 }); }
    // birds, bubbles
    const BIRDS = []; for (let k = 0; k < 18; k++) { const x = R(80, 1520), y = R(60, 400); if (x > 520 && x < 1150) continue; BIRDS.push({ x, y, s2: R(4, 9), v: R(8, 20), ph: R(0, TAU), lo: x < 800 ? 80 : 1150, hi: x < 800 ? 520 : 1540 }); }
    live(tt => BIRDS.forEach(b => { const span = b.hi - b.lo, x = b.lo + ((b.x - b.lo + tt * b.v) % span + span) % span, y = b.y + 4 * Math.sin(tt * 0.8 + b.ph), s2 = b.s2, f = 0.6 * Math.sin(tt * 7 + b.ph); P.curve([[x - s2, y + f * s2 * 0.5], [x - s2 * 0.4, y - s2 * (0.35 + f * 0.5)], [x, y]], { w: 1, c: K, passes: 1, rough: 0.1 }); P.curve([[x, y], [x + s2 * 0.4, y - s2 * (0.35 + f * 0.5)], [x + s2, y + f * s2 * 0.5]], { w: 1, c: K, passes: 1, rough: 0.1 }); }), { fps: 30 });
    P.text('CLOCK ISLAND', 1540, 966, { size: 10, align: 'right', a: 0.7 });
  }
});
