/* SHEET 16 — Ink Garden: a free-form abstract automatic doodle. A ragged organic mass grown on the page,
   packed with ~20 hand-inked motifs on black and white ground, with tendrils, spires and drips escaping outward. */
(window.SCENES = window.SCENES || []).push({
  name: 'Ink Garden', seed: 2718, ink: '#0b0b0b', theme: 'pencil',
  build(P, n, t) {
    const S = Sketch, TAU = S.TAU, lerp = S.lerp, K = '#0b0b0b', Wh = '#ffffff', R = (a, b) => P.r(a, b), pick = a => a[Math.floor(P.R() * a.length)];
    const black = pts => P.wash(pts, '#050505', 1, { edge: 0, jit: 0, steps: 1 });
    const white = pts => P.occlude(pts, Wh);
    const ol = (pts, w = 1.2, c = K) => P.path(pts.concat([pts[0]]), { w, c, a: 0.97, rough: 0.3, passes: 1 });
    const ln = (x1, y1, x2, y2, w = 0.8, c = K) => P.line(x1, y1, x2, y2, { w, c, passes: 1, over: 0, rough: 0.2 });
    const circ = (x, y, r, k = 16) => Array.from({ length: k }, (_, i) => [x + Math.cos(i * TAU / k) * r, y + Math.sin(i * TAU / k) * r]);
    const blobR = (cx, cy, rx, ry, ang = 0, k = 11, j = 0.16) => { const ca = Math.cos(ang), sa = Math.sin(ang); return P.sample(Array.from({ length: k }, (_, i) => { const a = i * TAU / k, u = Math.cos(a) * rx * R(1 - j, 1 + j), v = Math.sin(a) * ry * R(1 - j, 1 + j); return [cx + u * ca - v * sa, cy + u * sa + v * ca]; }), true, 2.5); };
    const shrink = (pts, cx, cy, k) => pts.map(([x, y]) => [cx + (x - cx) * k, cy + (y - cy) * k]);
    const dotRing = (pts, cx, cy, k = 0.84, gap = 6, r = 0.9, c = K) => { const q = shrink(pts, cx, cy, k), D = []; let acc = 0; for (let i = 1; i < q.length; i++) { acc += Math.hypot(q[i][0] - q[i - 1][0], q[i][1] - q[i - 1][1]); if (acc > gap) { acc = 0; D.push([q[i][0], q[i][1], r]); } } P.dots(D, c, 0.95); };
    const puffShade = (pts, cx, cy, r) => { for (let i = 0; i < pts.length; i += 2) { const [x, y] = pts[i], a = Math.atan2(y - cy, x - cx), lit = Math.cos(a + 2.4); if (lit > -0.15) continue; const L = r * 0.28 * -lit; for (let k = 0; k < 3; k++) { const s = 1.5 + k * 2.6; P.curve([[x - Math.cos(a) * s, y - Math.sin(a) * s], [x - Math.cos(a) * (s + L * 0.5) + Math.sin(a) * 1.5, y - Math.sin(a) * (s + L * 0.5) - Math.cos(a) * 1.5], [x - Math.cos(a) * (s + L), y - Math.sin(a) * (s + L)]], { w: 0.5, c: K, rough: 0.1, passes: 1 }); } } P.stipple(pts, Math.round(r * r * 0.35), { a: 0.9, r: 0.65, c: K, fade: (x, y) => Math.max(0, ((x - cx) + (y - cy)) / (r * 1.3)) }); };

    /* ---------------- the silhouette: a union of wobbly lobes along a wandering spine ---------------- */
    const lobes = []; { let x = 520, y = 760; for (let i = 0; i < 16; i++) { lobes.push([x, y, R(90, 175)]); x += R(20, 90) * (i % 5 === 4 ? -1.6 : 1); y += R(-120, 60); if (y < 250) y += 140; if (x > 1130) x -= 260; } lobes.push([800, 470, 210], [700, 330, 140], [960, 600, 150]); }
    const field = (x, y) => { let m = -1e9; for (const [cx, cy, r] of lobes) m = Math.max(m, r - Math.hypot(x - cx, y - cy)); return m + 18 * Math.sin(x * 0.021 + y * 0.013) + 12 * Math.sin(x * 0.047 - y * 0.031); };
    const inMask = (x, y, pad = 0) => field(x, y) > pad || (typeof darkPolys !== 'undefined' && darkPolys.some(p => S.pip(p, x, y) && S.pip(p, x + pad, y) && S.pip(p, x - pad, y) && S.pip(p, x, y + pad) && S.pip(p, x, y - pad)));
    const darkPolys = lobes.filter((_, i) => i % 3 === 1).map(([x, y, r]) => blobR(x + R(-30, 30), y + R(-30, 30), r * R(0.6, 0.85), r * R(0.55, 0.8), R(0, TAU), 13, 0.18));
    const inDark = (x, y) => darkPolys.some(p => S.pip(p, x, y));
    darkPolys.forEach(p => black(p));
    /* ---------------- motif vocabulary ---------------- */
    const M = {
      puff: (x, y, r) => { const p = blobR(x, y, r, r * R(0.75, 1), R(0, TAU), 12, 0.2); white(p); puffShade(p, x, y, r); ol(p, 1.3); },
      ripple: (x, y, r) => { white(circ(x, y, r, 28)); const n = Math.max(3, Math.round(r / 4)); for (let k = 1; k <= n; k++) P.circle(x, y, r * k / n, { w: k === n ? 1.4 : 0.6, c: K, passes: 1, rough: 0.2 }); P.dot(x, y, Math.max(1, r * 0.07), { c: K }); },
      eye: (x, y, r) => { const p = blobR(x, y, r, r * 0.78, R(-0.3, 0.3), 12, 0.1); white(p); ol(p, 1.4); dotRing(p, x, y, 0.86, 5, 0.9); P.circle(x, y, r * 0.42, { w: 1.1, c: K, passes: 1 }); for (let k = 0; k < 28; k++) { const a = k * TAU / 28; ln(x + Math.cos(a) * r * 0.2, y + Math.sin(a) * r * 0.2, x + Math.cos(a) * r * 0.41, y + Math.sin(a) * r * 0.41, 0.45); } black(circ(x, y, r * 0.17, 12)); P.dot(x - r * 0.06, y - r * 0.07, r * 0.05, { c: Wh, a: 1 }); },
      pod: (x, y, r) => { const a = R(0, TAU), p = blobR(x, y, r, r * 0.52, a, 12, 0.06); white(p); ol(p, 1.3); dotRing(p, x, y, 0.8, 5.5, 1); const core = blobR(x, y, r * 0.55, r * 0.2, a, 10, 0.04); black(core); for (let k = -3; k <= 3; k++) P.dot(x + Math.cos(a) * k * r * 0.14, y + Math.sin(a) * k * r * 0.14, 1.1, { c: Wh, a: 1 }); },
      cells: (x, y, r) => { const p = blobR(x, y, r, r * 0.9, 0, 12, 0.14); white(p); ol(p, 1.3); for (let i = 0; i < r * 1.4; i++) { const a = R(0, TAU), d = Math.sqrt(R(0, 1)) * r * 0.72, cx = x + Math.cos(a) * d, cy = y + Math.sin(a) * d, rr = R(1.6, r * 0.17); P.circle(cx, cy, rr, { w: 0.7, c: K, passes: 1 }); P.dot(cx, cy, rr * 0.35, { c: K }); } },
      shell: (x, y, r) => { white(circ(x, y, r, 24)); const sp = []; for (let a = 0; a < 3.2 * TAU; a += 0.14) sp.push([x + Math.cos(a) * r * (1 - a / (3.4 * TAU)), y + Math.sin(a) * r * (1 - a / (3.4 * TAU))]); P.path(sp, { w: 1.1, c: K, rough: 0.15, passes: 1 }); for (let i = 3; i < sp.length - 20; i += 3) { const j = Math.min(sp.length - 1, i + 45); ln(sp[i][0], sp[i][1], lerp(sp[i][0], sp[j][0], 0.35), lerp(sp[i][1], sp[j][1], 0.35), 0.45); } P.stipple(circ(x, y, r, 20), Math.round(r * r * 0.3), { a: 0.9, r: 0.6, c: K, fade: (px) => Math.max(0, (px - x) / r) }); P.circle(x, y, r, { w: 1.3, c: K, passes: 1 }); },
      honey: (x, y, r) => { const p = blobR(x, y, r, r * 0.9, 0, 12, 0.12); white(p); const s = Math.max(5, r / 5); for (let row = 0, yy = y - r; yy < y + r; yy += s * 0.87, row++) for (let xx = x - r + (row % 2) * s / 2; xx < x + r; xx += s) if (S.pip(shrink(p, x, y, 0.88), xx, yy)) { const hx = circ(xx, yy, s * 0.52, 6); P.poly(hx, { w: 0.55, c: K, passes: 1, over: 0, rough: 0.1 }); if (P.R() > 0.72) black(hx); } ol(p, 1.3); },
      bands: (x, y, r) => { const a = R(0, TAU), p = blobR(x, y, r, r * 0.42, a, 12, 0.04); white(p); const ca = Math.cos(a), sa = Math.sin(a); for (let k = -6; k <= 6; k++) { const u = k * r / 7, hw = r * 0.42 * Math.sqrt(Math.max(0, 1 - Math.pow(u / r, 2))); const A = [x + ca * u - sa * hw, y + sa * u + ca * hw], B = [x + ca * u + sa * hw, y + sa * u - ca * hw]; ln(A[0], A[1], B[0], B[1], 0.8); if (k % 2 === 0 && k < 6) { const u2 = u + r / 7, hw2 = r * 0.42 * Math.sqrt(Math.max(0, 1 - Math.pow(u2 / r, 2))); black([A, B, [x + ca * u2 + sa * hw2, y + sa * u2 - ca * hw2], [x + ca * u2 - sa * hw2, y + sa * u2 + ca * hw2]]); } } ol(p, 1.3); },
      mushroom: (x, y, r) => { const cap = [], by = y + r * 0.1; for (let k = 0; k <= 16; k++) { const a = Math.PI + k * Math.PI / 16; cap.push([x + Math.cos(a) * r, by + Math.sin(a) * r * 0.75]); } const cp = cap.concat([[x + r, by + r * 0.08], [x - r, by + r * 0.08]]); const stem = [[x - r * 0.18, by], [x + r * 0.18, by], [x + r * 0.22, y + r], [x - r * 0.22, y + r]]; white(stem); ol(stem, 1.1); P.hatch(stem, { ang: 90, gap: 1.8, a: 0.8, w: 0.4, c: K, fade: px => Math.max(0, (px - x) / (r * 0.2)) }); white(cp); for (let k = 1; k < 16; k++) { const a = Math.PI + k * Math.PI / 16; ln(x + Math.cos(a) * r * 0.2, by + r * 0.04, x + Math.cos(a) * r * 0.95, by + Math.sin(a) * r * 0.05 + r * 0.05, 0.4); } P.stipple(cap.concat([[x + r, by], [x - r, by]]), Math.round(r * r * 0.25), { a: 0.9, r: 0.6, c: K, fade: (px, py) => Math.max(0, (px - x) / r + 0.2) }); for (let k = 0; k < 5; k++) { const a = Math.PI + (k + 0.6) * Math.PI / 5.5; P.circle(x + Math.cos(a) * r * 0.55, by + Math.sin(a) * r * 0.45, r * 0.09, { w: 0.7, c: K, passes: 1 }); } ol(cp, 1.3); },
      rosette: (x, y, r) => { white(circ(x, y, r, 28)); const n = Math.round(R(9, 14)); for (let k = 0; k < n; k++) { const a = k * TAU / n, pts = blobR(x + Math.cos(a) * r * 0.55, y + Math.sin(a) * r * 0.55, r * 0.42, r * 0.17, a, 10, 0.03); ol(pts, 0.9); ln(x + Math.cos(a) * r * 0.25, y + Math.sin(a) * r * 0.25, x + Math.cos(a) * r * 0.85, y + Math.sin(a) * r * 0.85, 0.4); } white(circ(x, y, r * 0.24, 16)); P.circle(x, y, r * 0.24, { w: 1, c: K, passes: 1 }); P.stipple(circ(x, y, r * 0.22, 14), Math.round(r * 3), { a: 0.9, r: 0.6, c: K }); },
      scales: (x, y, r) => { const p = blobR(x, y, r, r * 0.85, 0, 12, 0.14); white(p); for (let yy = y - r; yy < y + r; yy += 6) for (let xx = x - r + ((yy / 6) % 2 ? 3.5 : 0); xx < x + r; xx += 7) if (S.pip(shrink(p, x, y, 0.9), xx, yy)) P.arc(xx, yy, 3.6, 3.6, 0.15, Math.PI - 0.15, { w: 0.6, c: K, passes: 1 }); ol(p, 1.3); },
      maze: (x, y, r) => { const p = blobR(x, y, r, r * 0.9, 0, 12, 0.14); white(p); for (let yy = y - r; yy < y + r; yy += 5) for (let xx = x - r; xx < x + r; xx += 5) if (S.pip(shrink(p, x, y, 0.9), xx + 2.5, yy + 2.5)) { if (P.R() > 0.5) ln(xx, yy, xx + 5, yy + 5, 0.7); else ln(xx + 5, yy, xx, yy + 5, 0.7); } ol(p, 1.3); },
      curl: (x, y, r) => { const pts = []; for (let a = 0; a < 2.6 * TAU; a += 0.12) { const rr = r * (1 - a / (2.9 * TAU)); pts.push([x + Math.cos(a) * rr, y + Math.sin(a) * rr, rr]); } const L = [], Rr = []; pts.forEach(([px, py, rr], i) => { const q = pts[Math.min(pts.length - 1, i + 1)], o = pts[Math.max(0, i - 1)], tx = q[0] - o[0], ty = q[1] - o[1], l = Math.hypot(tx, ty) || 1, w = Math.max(1, rr * 0.16); L.push([px - ty / l * w, py + tx / l * w]); Rr.push([px + ty / l * w, py - tx / l * w]); }); const poly = L.concat(Rr.slice().reverse()); white(poly); ol(poly, 1.1); for (let i = 2; i < pts.length; i += 3) { ln(L[i][0], L[i][1], Rr[i][0], Rr[i][1], 0.5); P.dot(pts[i][0], pts[i][1], Math.max(0.6, pts[i][2] * 0.05), { c: K }); } },
      coral: (x, y, r) => { const br = (bx, by, a, len, w, d) => { const ex = bx + Math.cos(a) * len, ey = by + Math.sin(a) * len; P.line(bx, by, ex, ey, { w: w + 2, c: K, passes: 1, over: 0, rough: 0.2 }); P.line(bx, by, ex, ey, { w, c: Wh, passes: 1, over: 0, rough: 0.2 }); if (d <= 0 || len < 4) { white(circ(ex, ey, w * 0.9 + 1, 10)); P.circle(ex, ey, w * 0.9 + 1, { w: 0.9, c: K, passes: 1 }); P.dot(ex, ey, 0.8, { c: K }); return; } br(ex, ey, a - R(0.3, 0.7), len * 0.72, w * 0.72, d - 1); br(ex, ey, a + R(0.3, 0.7), len * 0.72, w * 0.72, d - 1); }; br(x, y + r * 0.8, -Math.PI / 2 + R(-0.3, 0.3), r * 0.55, Math.max(2.5, r * 0.14), 4); },
      fern: (x, y, r) => { const a0 = R(0, TAU), rib = []; for (let k = 0; k <= 20; k++) { const t2 = k / 20, a = a0 + t2 * 1.1; rib.push([x + Math.cos(a0) * (t2 - 0.5) * 2 * r + Math.cos(a + Math.PI / 2) * Math.sin(t2 * Math.PI) * r * 0.25, y + Math.sin(a0) * (t2 - 0.5) * 2 * r + Math.sin(a + Math.PI / 2) * Math.sin(t2 * Math.PI) * r * 0.25]); } P.path(rib, { w: 1.2, c: K, rough: 0.1, passes: 1 }); for (let k = 1; k < 20; k++) { const [px, py] = rib[k], q = rib[k + 1], a = Math.atan2(q[1] - py, q[0] - px), L = r * 0.34 * Math.sin(k / 20 * Math.PI); [-1, 1].forEach(sg => { const lf = [[px, py], [px + Math.cos(a + sg * 1.0) * L * 0.6 - Math.cos(a) * 1.5, py + Math.sin(a + sg * 1.0) * L * 0.6 - Math.sin(a) * 1.5], [px + Math.cos(a + sg * 0.75) * L, py + Math.sin(a + sg * 0.75) * L], [px + Math.cos(a + sg * 0.5) * L * 0.6 + Math.cos(a) * 1.5, py + Math.sin(a + sg * 0.5) * L * 0.6 + Math.sin(a) * 1.5]]; const lp = P.sample(lf, true, 1.5); white(lp); ol(lp, 0.6); }); } },
      window: (x, y, r) => { const w = r * 0.62, h = r * 1.8, top = y - h / 2, bot = y + h / 2, arch = [[x - w, bot]]; for (let k = 0; k <= 16; k++) { const a = Math.PI + k * Math.PI / 16; arch.push([x + Math.cos(a) * w, top + w + Math.sin(a) * w]); } arch.push([x + w, bot]); white(arch); ol(arch, 1.4); const inner = shrink(arch, x, y + h * 0.05, 0.72); black(inner); dotRing(arch, x, y, 0.88, 5, 0.9); for (let k = 0; k < 5; k++) P.dot(x, top + w + k * h * 0.12, 1.2, { c: Wh, a: 1 }); const d = P.sample([[x, bot - h * 0.3], [x + 4, bot - h * 0.18], [x, bot - h * 0.12], [x - 4, bot - h * 0.18]], true, 1.5); white(d); },
      night: (x, y, r) => { const p = blobR(x, y, r, r * 0.9, 0, 11, 0.2); black(p); P.dots(Array.from({ length: Math.round(r * 1.3) }, () => { const a = R(0, TAU), d = Math.sqrt(R(0, 1)) * r * 0.8; return [x + Math.cos(a) * d, y + Math.sin(a) * d, R(0.4, 1.3)]; }), Wh, 1); ol(p, 1.2); },
      drips: (x, y, r) => { for (let k = -2; k <= 2; k++) { const dx = x + k * r * 0.34, L = r * R(0.6, 1.5); ln(dx, y - r, dx, y - r + L, 0.8); const ty = y - r + L, d = P.sample([[dx, ty - 4], [dx + 3.6, ty + 2], [dx, ty + 7], [dx - 3.6, ty + 2]], true, 1.5); white(d); ol(d, 0.9); } },
      stack: (x, y, r) => { let yy = y - r; while (yy < y + r) { const rr = R(3, r * 0.3), w = rr * R(1.2, 2); const e = circ(x, yy + rr, 1, 16).map(([px, py]) => [x + (px - x) * w, py + (py - yy - rr) * (rr - 1)]); white(e); ol(e, 1); if (P.R() > 0.5) P.hatch(e, { ang: 0, gap: 1.6, a: 0.8, w: 0.4, c: K }); yy += rr * 2 + 1; } },
    };
    const BIG = ['puff', 'puff', 'eye', 'ripple', 'pod', 'cells', 'shell', 'honey', 'bands', 'mushroom', 'rosette', 'scales', 'maze', 'curl', 'coral', 'fern', 'window', 'night', 'drips', 'stack', 'puff', 'cells'];
    const SMALL = ['puff', 'ripple', 'cells', 'eye', 'pod', 'bands', 'shell', 'night', 'puff', 'ripple'];

    /* ---------------- packing: largest first, a spatial grid for speed ---------------- */
    const G = 40, grid = new Map(), key = (i, j) => i * 1000 + j;
    const addC = (x, y, r) => { const i0 = Math.floor((x - r) / G), i1 = Math.floor((x + r) / G), j0 = Math.floor((y - r) / G), j1 = Math.floor((y + r) / G); for (let i = i0; i <= i1; i++) for (let j = j0; j <= j1; j++) { const k = key(i, j); if (!grid.has(k)) grid.set(k, []); grid.get(k).push([x, y, r]); } };
    const clear = (x, y, r, pad = 2) => { const i0 = Math.floor((x - r - 80) / G), i1 = Math.floor((x + r + 80) / G), j0 = Math.floor((y - r - 80) / G), j1 = Math.floor((y + r + 80) / G); for (let i = i0; i <= i1; i++) for (let j = j0; j <= j1; j++) { const L = grid.get(key(i, j)); if (L) for (const [a, b, c] of L) if (Math.hypot(x - a, y - b) < c + r + pad) return false; } return true; };
    let placed = 0;
    let bx0 = 1e9, bx1 = -1e9, by0 = 1e9, by1 = -1e9; lobes.forEach(([x, y, r]) => { bx0 = Math.min(bx0, x - r - 30); bx1 = Math.max(bx1, x + r + 30); by0 = Math.min(by0, y - r - 30); by1 = Math.max(by1, y + r + 30); }); bx0 = Math.max(80, bx0); bx1 = Math.min(1520, bx1); by0 = Math.max(70, by0); by1 = Math.min(930, by1);
    [[58, 80], [46, 200], [36, 400], [28, 700], [21, 1100], [16, 1700], [12, 2600], [9, 3600], [6, 5000], [4, 6000], [2.6, 7000]].forEach(([r0, tries]) => {
      for (let i = 0; i < tries * 14; i++) { const r = r0 * R(0.8, 1.2), x = R(bx0, bx1), y = R(by0, by1); if (!inMask(x, y, r * 0.35) || !clear(x, y, r)) continue; addC(x, y, r); placed++;
        if (r0 <= 6 || (r0 <= 9 && P.R() > 0.6)) { if (inDark(x, y)) { if (P.R() > 0.4) P.dot(x, y, r * 0.45, { c: Wh, a: 1 }); else { white(circ(x, y, r, 10)); P.circle(x, y, r, { w: 0.8, c: K, passes: 1 }); P.dot(x, y, r * 0.3, { c: K }); } } else { if (P.R() > 0.5) P.circle(x, y, r, { w: 0.8, c: K, passes: 1 }); else P.dot(x, y, r * 0.5, { c: K }); } continue; }
        let kind = r0 >= 12 ? pick(BIG) : pick(SMALL); while (inDark(x, y) && (kind === 'drips' || kind === 'night' || kind === 'fern' || kind === 'coral')) kind = pick(BIG); M[kind](x, y, r); if (r > 24 && P.R() > 0.55) ol(circ(x, y, r * 1.08, 24), 0.5); }
    });
    // white wiggles and lightning through the dark zones, stipple haze in white gaps near the mass
    for (let k = 0; k < 900; k++) { let x = R(90, 1510), y = R(80, 920); if (!inDark(x, y)) continue; const pts = [[x, y]]; let a = R(0, TAU); for (let i = 0; i < 18; i++) { a += R(-0.8, 0.8); x += Math.cos(a) * 5; y += Math.sin(a) * 5; if (!inDark(x, y) || !clear(x, y, 1, 0)) break; pts.push([x, y]); } if (pts.length > 3) P.path(pts, { w: 0.8, c: Wh, a: 1, rough: 0.1, passes: 1 }); }
    { const W2 = []; for (let i = 0; i < 20000 && W2.length < 1400; i++) { const x = R(80, 1520), y = R(70, 930); if (!inDark(x, y) || !clear(x, y, 0.8, 0.4)) continue; W2.push([x, y, R(0.4, 1.1)]); } P.dots(W2, Wh, 1); }
    { const D2 = []; for (let i = 0; i < 26000 && D2.length < 5200; i++) { const x = R(70, 1530), y = R(60, 940); if (!inMask(x, y, -6) || inDark(x, y) || !clear(x, y, 0.6, 0.3)) continue; D2.push([x, y, R(0.35, 0.8)]); } P.dots(D2, K, 0.85); }

    /* ---------------- things escaping the mass: tendrils, bead chains, striped feelers, spires, bubbles ---------------- */
    const cx0 = 800, cy0 = 500;
    const edgePts = []; for (let i = 0; i < 40000 && edgePts.length < 90; i++) { const x = R(90, 1510), y = R(70, 930), f = field(x, y); if (f > 0 && f < 8 && !inMask(x + (x - cx0) * 0.08, y + (y - cy0) * 0.08, 0)) edgePts.push([x, y]); }
    edgePts.forEach(([x, y], i) => { let a = Math.atan2(y - cy0, x - cx0) + R(-0.5, 0.5), curl = R(-0.06, 0.06); const pts = [[x, y]], L = R(40, 200); for (let s = 0; s < L; s += 6) { a += curl; curl *= 1.03; x += Math.cos(a) * 6; y += Math.sin(a) * 6; if (x < 60 || x > 1540 || y < 55 || y > 945 || inMask(x, y, 4)) break; pts.push([x, y]); } if (pts.length < 5) return;
      const kind = i % 5, end = pts[pts.length - 1];
      if (kind === 0) { P.path(pts, { w: 1, c: K, rough: 0.2, passes: 1 }); const d = P.sample([[end[0], end[1] - 4], [end[0] + 4, end[1] + 2], [end[0], end[1] + 8], [end[0] - 4, end[1] + 2]], true, 1.5); white(d); ol(d, 1); }
      else if (kind === 1) { pts.forEach(([px, py], k) => { if (k % 2) return; const rr = 4.5 * (1 - k / pts.length) + 1.2; white(circ(px, py, rr, 10)); P.circle(px, py, rr, { w: 0.9, c: K, passes: 1 }); P.dot(px, py, rr * 0.3, { c: K }); }); }
      else if (kind === 2) { const Lf = [], Rt = []; pts.forEach((p, k) => { const q = pts[Math.min(pts.length - 1, k + 1)], o = pts[Math.max(0, k - 1)], tx = q[0] - o[0], ty = q[1] - o[1], l = Math.hypot(tx, ty) || 1, w = 7 * (1 - k / pts.length) + 1; Lf.push([p[0] - ty / l * w, p[1] + tx / l * w]); Rt.push([p[0] + ty / l * w, p[1] - tx / l * w]); }); const poly = Lf.concat(Rt.slice().reverse()); white(poly); ol(poly, 1.1); for (let k = 1; k < pts.length - 1; k += 2) { ln(Lf[k][0], Lf[k][1], Rt[k][0], Rt[k][1], 0.7); if (k % 4 === 1 && k + 2 < pts.length) black([Lf[k], Lf[k + 1], Rt[k + 1], Rt[k]]); } }
      else if (kind === 3) { P.path(pts, { w: 0.7, c: K, rough: 0.2, passes: 1 }); P.path(pts.map(([px, py]) => [px + 2.4, py + 1]), { w: 0.7, c: K, rough: 0.2, passes: 1 }); pts.forEach(([px, py], k) => { if (k % 3 === 0) P.dot(px + 1.2, py + 0.5, 1, { c: K }); }); white(circ(end[0], end[1], 6, 14)); P.circle(end[0], end[1], 6, { w: 1.1, c: K, passes: 1 }); P.circle(end[0], end[1], 2.5, { w: 0.8, c: K, passes: 1 }); }
      else { P.path(pts, { w: 1.2, c: K, rough: 0.2, passes: 1 }); for (let k = 2; k < pts.length; k += 3) { const [px, py] = pts[k], q = pts[k - 1], a2 = Math.atan2(py - q[1], px - q[0]) + Math.PI / 2; ln(px, py, px + Math.cos(a2) * 5, py + Math.sin(a2) * 5, 0.7); P.dot(px + Math.cos(a2) * 5.5, py + Math.sin(a2) * 5.5, 1.1, { c: K }); } }
    });
    // beaded spires rising off the top of the mass
    for (let i = 0; i < 9; i++) { let bx = 0, by = 1e9; for (let k = 0; k < 400; k++) { const x = R(430, 1170), y = R(80, 700); if (field(x, y) > 0 && field(x, y) < 10 && !inMask(x, y - 12, 0) && y < by) { bx = x; by = y; } } if (!bx) continue; const h = R(60, 150), top = Math.max(70, by - h); ln(bx, by, bx, top, 1.3); let yy = by - 10; let k2 = 0; while (yy > top + 12) { const s = pick([0, 1, 2]); if (s === 0) { white(circ(bx, yy, 5.5, 12)); P.circle(bx, yy, 5.5, { w: 1, c: K, passes: 1 }); P.dot(bx, yy, 1.8, { c: K }); } else if (s === 1) { const d = [[bx, yy - 7], [bx + 5, yy], [bx, yy + 7], [bx - 5, yy]]; white(d); P.poly(d, { w: 1, c: K, passes: 1, over: 0 }); if (k2 % 2) black(shrink(d, bx, yy, 0.5)); } else { P.rect(bx - 3.5, yy - 5, 7, 10, { w: 0.9, c: K, passes: 1, over: 0 }); ln(bx - 3.5, yy, bx + 3.5, yy, 0.6); } yy -= 15; k2++; } const tip = [[bx, top - 18], [bx + 6, top], [bx, top + 4], [bx - 6, top]]; white(tip); P.poly(tip, { w: 1.1, c: K, passes: 1, over: 0 }); P.dot(bx, top - 5, 1.4, { c: K }); }
    // bubbles and specks drifting off, thinning with distance
    for (let i = 0; i < 9000; i++) { const x = R(70, 1530), y = R(60, 940), f = field(x, y); if (f > -4) continue; if (P.R() > Math.exp(f / 45)) continue; if (!clear(x, y, 3, 1)) continue; const r = R(0.8, 6.5) * Math.exp(f / 160); addC(x, y, r); if (r > 3) { P.circle(x, y, r, { w: 0.8, c: K, passes: 1 }); P.arc(x, y, r * 0.6, r * 0.6, 3.6, 4.6, { w: 0.5, c: K, passes: 1 }); } else P.dot(x, y, Math.max(0.5, r * 0.5), { c: K, a: 0.9 }); }
    P.text('INK GARDEN  -  GROWN, NOT PLANNED', 1540, 966, { size: 9, align: 'right', a: 0.6 });
  }
});
